#!/data/data/com.termux/files/usr/bin/bash
# Bootstrap a Termux Fractanet node (Android) for SSH mesh parity with Linux peers.
#
# Prerequisites (outside this script):
#   - Tailscale app joined to tailnet (hostname e.g. poco-jhr)
#   - Termux: pkg install openssh; sshd on port 8022; password or key for first inbound SSH
#   - Termux:Boot (com.termux.boot) for sshd at Android boot — install-termux-boot.ps1
#
# Run ON the device (or via ssh poco-jhr from ThinkPad):
#   FRACTANET_MESH_PUBKEY="ssh-ed25519 ..." bash fractanet-termux-bootstrap.sh
#
# Optional env:
#   NODE_HOSTNAME=poco-jhr
#   FRACTA_TS_IP=100.91.12.74
#   THINKPAD_TS_IP=100.122.121.68
#   RPI3_TS_IP=100.117.135.27
#   TERMUX_USER=jh

set -euo pipefail

NODE_HOSTNAME="${NODE_HOSTNAME:-poco-jhr}"
TERMUX_USER="${TERMUX_USER:-${USER}}"
FRACTA_TS_IP="${FRACTA_TS_IP:-100.91.12.74}"
THINKPAD_TS_IP="${THINKPAD_TS_IP:-100.122.121.68}"
RPI3_TS_IP="${RPI3_TS_IP:-100.117.135.27}"
LAYOUT_SCRIPT="${LAYOUT_SCRIPT:-${HOME}/fractanet-termux-layout.sh}"

if [[ -z "${FRACTANET_MESH_PUBKEY:-}" ]]; then
  echo "error: set FRACTANET_MESH_PUBKEY (ssh-ed25519 ...)" >&2
  exit 2
fi

echo "[fractanet-termux] hostname=${NODE_HOSTNAME} user=${TERMUX_USER}"

if ! command -v ssh >/dev/null 2>&1 || ! command -v sshd >/dev/null 2>&1; then
  echo "[fractanet-termux] installing openssh..."
  pkg install -y openssh
fi

if ! command -v termux-wake-lock >/dev/null 2>&1; then
  pkg install -y termux-api || true
fi

bash "${LAYOUT_SCRIPT}"

mkdir -p "${HOME}/.ssh" "${HOME}/.termux/boot"
chmod 700 "${HOME}/.ssh"
touch "${HOME}/.ssh/authorized_keys"
chmod 600 "${HOME}/.ssh/authorized_keys"
if ! grep -qF 'fractanet-mesh' "${HOME}/.ssh/authorized_keys" 2>/dev/null; then
  echo "${FRACTANET_MESH_PUBKEY}" >> "${HOME}/.ssh/authorized_keys"
fi

cat > "${HOME}/.termux/boot/sshd" <<'BOOT'
#!/data/data/com.termux/files/usr/bin/sh
termux-wake-lock
sshd
BOOT
chmod +x "${HOME}/.termux/boot/sshd"

cat > "${HOME}/.ssh/config" <<EOF
# --- Fractanet mesh (generated by fractanet-termux-bootstrap.sh) ---
Host fracta thinkpad i7-thinkpad-jhr rpi3-view fracta-ts
    StrictHostKeyChecking accept-new

Host thinkpad i7-thinkpad-jhr
    HostName ${THINKPAD_TS_IP}
    User admin
    Port 22
    IdentityFile ~/.ssh/fractanet-mesh
    IdentitiesOnly yes
    ServerAliveInterval 30

Host fracta-ts fracta
    HostName ${FRACTA_TS_IP}
    User ubuntu
    Port 22
    IdentityFile ~/.ssh/fractanet-mesh
    IdentitiesOnly yes
    ServerAliveInterval 30

Host rpi3-view
    HostName ${RPI3_TS_IP}
    User jh
    Port 22
    IdentityFile ~/.ssh/fractanet-mesh
    IdentitiesOnly yes
    ServerAliveInterval 30

Host poco-jhr
    HostName 100.97.223.45
    User ${TERMUX_USER}
    Port 8022
    IdentityFile ~/.ssh/fractanet-mesh
    IdentitiesOnly yes
    ServerAliveInterval 30
EOF
chmod 600 "${HOME}/.ssh/config"

if pgrep -x sshd >/dev/null 2>&1; then
  echo "[fractanet-termux] sshd already running"
else
  termux-wake-lock || true
  sshd
  echo "[fractanet-termux] sshd started"
fi

echo "[fractanet-termux] done"
echo "  inbound:  ssh ${TERMUX_USER}@poco-jhr  (port 8022 from peers)"
echo ""
echo "Next (from ThinkPad — never commit private key):"
echo "  scp -P 8022 ~/.cogentia/secrets/fractanet-mesh ${TERMUX_USER}@poco-jhr:~/.ssh/fractanet-mesh"
echo "  ssh poco-jhr 'chmod 600 ~/.ssh/fractanet-mesh && ssh fracta hostname'"