#!/data/data/com.termux/files/usr/bin/bash
# Codex + Claude Code inside Ubuntu proot (glibc linux-arm64).
# Grok Build runs natively on Termux — use `grok` directly.
#
# Also installs Fractanet mesh SSH into proot /root/.ssh so agents can
# `ssh fracta` (proot HOME is /root, not Termux $HOME — bare "fracta"
# does not resolve without Host aliases).
#
# Usage: bash ~/fractanet-mobile-proot-agents.sh

set -euo pipefail

PROOT_NAME="${PROOT_NAME:-ubuntu}"
WRAPPER_DIR="${HOME}/.local/bin"
mkdir -p "${WRAPPER_DIR}"

if ! proot-distro login "${PROOT_NAME}" -- true >/dev/null 2>&1; then
  echo "[proot] installing ubuntu:24.04..."
  proot-distro install ubuntu:24.04
fi

# Mesh IPs (override via env when tailnet addresses change)
FRACTA_TS_IP="${FRACTA_TS_IP:-100.91.12.74}"
THINKPAD_TS_IP="${THINKPAD_TS_IP:-100.122.121.68}"
RPI3_TS_IP="${RPI3_TS_IP:-100.117.135.27}"
POCO_TS_IP="${POCO_TS_IP:-100.97.223.45}"
TERMUX_SSH_DIR="${TERMUX_SSH_DIR:-${HOME}/.ssh}"

echo "[proot] node 22 + agents + mesh SSH in ${PROOT_NAME}..."

# Write mesh config on Termux side, then copy into proot (avoids nested quoting hell).
MESH_CFG_TMP="$(mktemp)"
cat > "${MESH_CFG_TMP}" <<EOF
# Fractanet mesh — proot (generated by fractanet-mobile-proot-agents.sh)
# Key lives at /root/.ssh/fractanet-mesh (copied from Termux on each setup).
Host thinkpad i7-thinkpad-jhr
    HostName ${THINKPAD_TS_IP}
    User admin
    Port 22
    IdentityFile /root/.ssh/fractanet-mesh
    IdentitiesOnly yes
    ServerAliveInterval 30
    StrictHostKeyChecking accept-new

Host fracta-ts fracta
    HostName ${FRACTA_TS_IP}
    User ubuntu
    Port 22
    IdentityFile /root/.ssh/fractanet-mesh
    IdentitiesOnly yes
    ServerAliveInterval 30
    StrictHostKeyChecking accept-new

Host rpi3-view
    HostName ${RPI3_TS_IP}
    User jh
    Port 22
    IdentityFile /root/.ssh/fractanet-mesh
    IdentitiesOnly yes
    ServerAliveInterval 30
    StrictHostKeyChecking accept-new

Host poco-jhr
    HostName ${POCO_TS_IP}
    User jh
    Port 8022
    IdentityFile /root/.ssh/fractanet-mesh
    IdentitiesOnly yes
    ServerAliveInterval 30
    StrictHostKeyChecking accept-new
EOF

proot-distro login "${PROOT_NAME}" -- bash --noprofile --norc -c "
set -e
export DEBIAN_FRONTEND=noninteractive PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
if ! command -v node >/dev/null || [ \"\$(node -v | cut -d. -f1 | tr -d v)\" -lt 20 ]; then
  apt-get update -qq
  apt-get install -y -qq curl ca-certificates
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  apt-get install -y -qq nodejs
fi
command -v ssh >/dev/null || { apt-get update -qq; apt-get install -y -qq openssh-client; }
npm install -g @openai/codex @anthropic-ai/claude-code --allow-scripts=@anthropic-ai/claude-code
mkdir -p /root/.codex /root/.claude /root/.ssh
chmod 700 /root/.ssh
T=/data/data/com.termux/files/home
[ -f \"\$T/.codex/auth.json\" ] && cp \"\$T/.codex/auth.json\" /root/.codex/auth.json
[ -f \"\$T/.claude/.credentials.json\" ] && cp \"\$T/.claude/.credentials.json\" /root/.claude/.credentials.json
chmod 600 /root/.codex/auth.json /root/.claude/.credentials.json 2>/dev/null || true
if [ -f \"\$T/.ssh/fractanet-mesh\" ]; then
  cp -f \"\$T/.ssh/fractanet-mesh\" /root/.ssh/fractanet-mesh
  chmod 600 /root/.ssh/fractanet-mesh
fi
if [ -f \"\$T/.ssh/known_hosts\" ]; then
  cp -f \"\$T/.ssh/known_hosts\" /root/.ssh/known_hosts
  chmod 600 /root/.ssh/known_hosts
fi
codex --version
claude --version
"

# Copy mesh config into proot after login (path is shared FS on Termux)
proot-distro login "${PROOT_NAME}" -- bash --noprofile --norc -c "
set -e
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
mkdir -p /root/.ssh && chmod 700 /root/.ssh
cp -f '${MESH_CFG_TMP}' /root/.ssh/config
chmod 600 /root/.ssh/config
if [ ! -f /root/.ssh/fractanet-mesh ] && [ -f '${TERMUX_SSH_DIR}/fractanet-mesh' ]; then
  cp -f '${TERMUX_SSH_DIR}/fractanet-mesh' /root/.ssh/fractanet-mesh
  chmod 600 /root/.ssh/fractanet-mesh
fi
echo '[proot] verifying ssh fracta...'
if [ -f /root/.ssh/fractanet-mesh ]; then
  ssh -o BatchMode=yes -o ConnectTimeout=12 fracta 'hostname; whoami' || echo '[proot] WARN: ssh fracta failed (Tailscale up? key authorized?)'
else
  echo '[proot] WARN: no fractanet-mesh key — copy from Termux ~/.ssh first'
fi
"
rm -f "${MESH_CFG_TMP}"

cat > "${WRAPPER_DIR}/agent-codex" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
exec proot-distro login ubuntu -- bash --noprofile --norc -c 'export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin; cd /data/data/com.termux/files/home/srv/cogentia/repos && exec codex "$@"' -- "$@"
EOF
cat > "${WRAPPER_DIR}/agent-claude" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
exec proot-distro login ubuntu -- bash --noprofile --norc -c 'export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin; cd /data/data/com.termux/files/home/srv/cogentia/repos && exec claude "$@"' -- "$@"
EOF
chmod +x "${WRAPPER_DIR}/agent-codex" "${WRAPPER_DIR}/agent-claude"
ln -sf agent-codex "${WRAPPER_DIR}/codex"
ln -sf agent-claude "${WRAPPER_DIR}/claude"

touch "${HOME}/.profile"
chmod 600 "${HOME}/.profile"
grep -q 'source.*bashrc' "${HOME}/.profile" 2>/dev/null || cat > "${HOME}/.profile" <<'EOF'
# Termux login shell — source interactive config
if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi
EOF

grep -q 'Fractanet mobile dev' "${HOME}/.bashrc" 2>/dev/null || cat >> "${HOME}/.bashrc" <<'EOF'

# Fractanet mobile dev (proot wrappers + grok native)
export PATH="$HOME/.local/bin:$HOME/.grok/bin:$PATH"
EOF

echo "[proot] codex/claude -> agent wrappers in ~/.local/bin; grok native: grok"
echo "[proot] mesh SSH in proot: ssh fracta (needs Tailscale Android + fractanet-mesh key)"
echo "[proot] ~/.profile sources ~/.bashrc on Termux startup"
