#!/usr/bin/env bash
# Bootstrap a Linux Fractanet node (Raspberry Pi OS, Ubuntu, …) onto the tailnet with SSH mesh.
#
# Minimum outcome: inbound SSH over Tailscale (fractanet-mesh key) + outbound SSH to peers.
#
# Run ON the new node (as user with sudo). From ThinkPad (first boot on LAN):
#   scp fractanet-node-bootstrap.sh pi@<pi-lan-ip>:~
#   ssh pi@<pi-lan-ip> 'NODE_HOSTNAME=rpi3-view TAILSCALE_AUTH_KEY=tskey-auth-... FRACTANET_MESH_PUBKEY="ssh-ed25519 ..." bash ~/fractanet-node-bootstrap.sh'
#
# Required env:
#   TAILSCALE_AUTH_KEY=tskey-auth-...        # reusable bootstrap key until Pi+phone enrolled
#   FRACTANET_MESH_PUBKEY="ssh-ed25519 ..."
# Optional:
#   NODE_HOSTNAME=rpi3-view
#   TAILNET_USER=pi
#   FRACTA_TS_IP=100.91.12.74
#   THINKPAD_TS_IP=100.122.121.68
#   ENABLE_POSTURE_CHECKING=1

set -euo pipefail

NODE_HOSTNAME="${NODE_HOSTNAME:-$(hostname -s)}"
TAILNET_USER="${TAILNET_USER:-${USER}}"
FRACTA_TS_IP="${FRACTA_TS_IP:-100.91.12.74}"
THINKPAD_TS_IP="${THINKPAD_TS_IP:-100.122.121.68}"

if [[ -z "${TAILSCALE_AUTH_KEY:-}" ]]; then
  echo "error: set TAILSCALE_AUTH_KEY (tskey-auth-...)" >&2
  exit 2
fi
if [[ -z "${FRACTANET_MESH_PUBKEY:-}" ]]; then
  echo "error: set FRACTANET_MESH_PUBKEY (ssh-ed25519 ...)" >&2
  exit 2
fi

echo "[fractanet] hostname=${NODE_HOSTNAME} user=${TAILNET_USER}"

if [[ "$(hostname -s)" != "${NODE_HOSTNAME}" ]]; then
  echo "[fractanet] setting hostname -> ${NODE_HOSTNAME}"
  if ! grep -q "${NODE_HOSTNAME}" /etc/hosts 2>/dev/null; then
    echo "127.0.1.1 ${NODE_HOSTNAME}" | sudo tee -a /etc/hosts >/dev/null
  fi
  sudo hostnamectl set-hostname "${NODE_HOSTNAME}"
fi

if ! command -v tailscale >/dev/null 2>&1; then
  echo "[fractanet] installing Tailscale..."
  curl -fsSL https://tailscale.com/install.sh | sh
fi

sudo tailscale up \
  --auth-key="${TAILSCALE_AUTH_KEY}" \
  --hostname="${NODE_HOSTNAME}" \
  --accept-routes \
  --accept-dns

echo "[fractanet] installing openssh-server..."
sudo apt-get update -qq
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server

sudo systemctl enable ssh.socket ssh.service
sudo systemctl start ssh.socket ssh.service

mkdir -p "${HOME}/.ssh"
chmod 700 "${HOME}/.ssh"
touch "${HOME}/.ssh/authorized_keys"
chmod 600 "${HOME}/.ssh/authorized_keys"
if ! grep -qF "${FRACTANET_MESH_PUBKEY}" "${HOME}/.ssh/authorized_keys" 2>/dev/null; then
  echo "${FRACTANET_MESH_PUBKEY}" >> "${HOME}/.ssh/authorized_keys"
fi

if [[ ! -f "${HOME}/.ssh/config" ]] || ! grep -q 'Host fracta' "${HOME}/.ssh/config" 2>/dev/null; then
  cat >> "${HOME}/.ssh/config" <<EOF

# --- Fractanet mesh (generated by fractanet-node-bootstrap.sh) ---
Host thinkpad i7-thinkpad-jhr
    HostName ${THINKPAD_TS_IP}
    User admin
    IdentityFile ~/.ssh/fractanet-mesh
    IdentitiesOnly yes

Host fracta-ts fracta
    HostName ${FRACTA_TS_IP}
    User ubuntu
    IdentityFile ~/.ssh/fractanet-mesh
    IdentitiesOnly yes

Host rpi3-view
    HostName ${NODE_HOSTNAME}
    User ${TAILNET_USER}
    IdentityFile ~/.ssh/fractanet-mesh
    IdentitiesOnly yes
EOF
  chmod 600 "${HOME}/.ssh/config"
  echo "[fractanet] wrote ~/.ssh/config"
fi

if [[ "${ENABLE_POSTURE_CHECKING:-}" == "1" ]]; then
  sudo tailscale set --posture-checking=true
  echo "[fractanet] posture-checking enabled (reconnect tailscale if needed)"
fi

TS_IP="$(tailscale ip -4 2>/dev/null || true)"
echo "[fractanet] done"
echo "  tailscale_ip: ${TS_IP:-pending}"
echo "  inbound:  ssh ${TAILNET_USER}@${TS_IP:-${NODE_HOSTNAME}}"
echo "  magicdns: ssh ${NODE_HOSTNAME}  (from any tailnet peer)"
echo ""
echo "Next (on ThinkPad, from repo secrets — never commit):"
echo "  scp ~/.cogentia/secrets/fractanet-mesh ${TAILNET_USER}@${NODE_HOSTNAME}:~/.ssh/fractanet-mesh"
echo "  ssh ${NODE_HOSTNAME} 'chmod 600 ~/.ssh/fractanet-mesh'"
echo "  ssh ${NODE_HOSTNAME} 'ssh fracta hostname && ssh thinkpad hostname'"