# Install Agent CLI Gateway on Windows (ThinkPad / dev workstation).
#
# Lifetime model (Linux analog: systemd Type=simple):
#   Logon scheduled task runs run-agent-gateway-windows-foreground.ps1 which
#   blocks on node agent-gateway.js — Task Scheduler owns process lifetime.
#
# Usage:
#   pwsh -File install-agent-gateway-windows.ps1 -Bind tailscale
#   pwsh -File install-agent-gateway-windows.ps1 -Bind tailscale -RegisterStartupTask
#   pwsh -File install-agent-gateway-windows.ps1 -Bind tailscale -RegisterStartupTask -StartTask

param(
    [ValidateSet('loopback', 'tailscale', 'all')]
    [string]$Bind = 'loopback',
    [int]$Port = 8793,
    [int]$MaxConcurrent = 8,
    [switch]$Start,
    [switch]$RegisterStartupTask,
    [switch]$StartTask,
    [string]$InsemeEnv = ''
)

$ErrorActionPreference = 'Stop'
$nodeSlug = ([System.Net.Dns]::GetHostName()).ToLower()
$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$secretsDir = Join-Path $env:USERPROFILE '.cogentia\secrets'
$varDir = Join-Path $env:USERPROFILE '.cogentia\var'
$envFile = Join-Path $secretsDir 'agent-gateway.env'
$bootScript = Join-Path $secretsDir "boot-agent-gateway-$nodeSlug.ps1"
$foregroundRunner = Join-Path $PSScriptRoot 'run-agent-gateway-windows-foreground.ps1'

New-Item -ItemType Directory -Force -Path $secretsDir, $varDir | Out-Null

function Get-DotEnvValue([string]$Path, [string]$Key) {
    if (-not (Test-Path $Path)) { return $null }
    foreach ($line in Get-Content $Path) {
        if ($line -match "^\s*(?:export\s+)?$([regex]::Escape($Key))\s*=\s*(.*)\s*$") {
            $value = $Matches[1].Trim().Trim("'").Trim('"')
            return $value
        }
    }
    return $null
}

# Prefer existing COGENTIA_API_KEY (SoT: inseme/.env). Never invent a parallel AGENT_GATEWAY_TOKEN.
$apiKey = Get-DotEnvValue $envFile 'COGENTIA_API_KEY'
if (-not $apiKey) {
    if (-not $InsemeEnv) {
        $candidate = Join-Path $root '..\inseme\.env'
        if (Test-Path $candidate) { $InsemeEnv = (Resolve-Path $candidate).Path }
    }
    if ($InsemeEnv -and (Test-Path $InsemeEnv)) {
        $apiKey = Get-DotEnvValue $InsemeEnv 'COGENTIA_API_KEY'
    }
}
if (-not $apiKey) {
    $apiKey = $env:COGENTIA_API_KEY
}
if (-not $apiKey -and $Bind -ne 'loopback') {
    throw 'COGENTIA_API_KEY required for non-loopback bind (copy from inseme/.env authority)'
}

$lines = @(
    '# Agent CLI Gateway — runtime copy. Authority: inseme/.env (COGENTIA_API_KEY only).'
    '# Do NOT set AGENT_GATEWAY_TOKEN to the same secret (legacy read alias only in code).'
    "AGENT_GATEWAY_BIND=$Bind"
    "AGENT_GATEWAY_PORT=$Port"
    "AGENT_GATEWAY_REPO_ROOTS=$root"
    "AGENT_GATEWAY_MAX_CONCURRENT=$MaxConcurrent"
)
if ($apiKey) {
    $lines += "COGENTIA_API_KEY=$apiKey"
}
Set-Content -Path $envFile -Value ($lines -join "`n") -Encoding utf8
Write-Host "[agent-gateway] wrote $envFile (bind=$Bind port=$Port key_set=$([bool]$apiKey))"

# Boot shim kept for MagicDNS hostname discovery; always calls the blocking runner.
$bootBody = @"
# Generated by install-agent-gateway-windows.ps1 — long-running gateway under Task Scheduler.
`$ErrorActionPreference = 'Stop'
& '$foregroundRunner' -EnvFile '$envFile' -RepoRoot '$root' -Port $Port
"@
Set-Content -Path $bootScript -Value $bootBody -Encoding utf8
Write-Host "[agent-gateway] wrote $bootScript"

Write-Host @"

Lifetime (foreground / debug):
  pwsh -NoProfile -File $foregroundRunner -EnvFile $envFile -Port $Port

Start (one-shot helper that detaches — prefer task for durability):
  node $PSScriptRoot\start-agent-gateway-windows.js --env-file $envFile --port $Port

Health:
  curl "http://127.0.0.1:$Port/health?quick=1" -H "Authorization: Bearer <COGENTIA_API_KEY>"

"@

if ($RegisterStartupTask) {
    $taskName = 'CogentiaAgentGateway'
    $helper = Join-Path $PSScriptRoot 'lib\register-hidden-node-task.ps1'
    . $helper
    $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
    Register-HiddenPwshTask `
        -TaskName $taskName `
        -ScriptPath $bootScript `
        -WorkingDirectory $root `
        -Triggers @($trigger) `
        -RunAsUser $env:USERNAME `
        -Description "Agent CLI Gateway (long-running, logon) — $nodeSlug"
    Write-Host "[agent-gateway] registered logon task: $taskName (unlimited ExecutionTimeLimit, restart x3)"

    if ($StartTask) {
        Write-Host "[agent-gateway] starting task $taskName..."
        Start-ScheduledTask -TaskName $taskName
        Start-Sleep -Seconds 5
        $info = Get-ScheduledTaskInfo -TaskName $taskName
        Write-Host "[agent-gateway] task last result=$($info.LastTaskResult) state=$((Get-ScheduledTask -TaskName $taskName).State)"
    }
}

if ($Start) {
    & $foregroundRunner -EnvFile $envFile -RepoRoot $root -Port $Port
}
