import fs from "node:fs";
import path from "node:path";

/**
 * Static seed concept aliases (S3)
 * Ensures load-bearing doctrines resolve deterministically.
 */
export const SEED_CONCEPT_ALIASES = [
  {
    name: "Potentics",
    aliases: ["potentics", "science des possibles", "transition possibiliste", "potentialite graduee"],
    canonical_repo: "barons-Mariani",
    canonical_rel: "research/potentics.md",
    canonical_url: "https://github.com/JeanHuguesRobert/barons-Mariani/blob/main/research/potentics.md"
  },
  {
    name: "Channels Fragmentation",
    aliases: ["fragmentation des canaux", "channel fragmentation", "canaux fragmentes", "vigilia"],
    canonical_repo: "barons-Mariani",
    canonical_rel: "research/vigilia.md",
    canonical_url: "https://github.com/JeanHuguesRobert/barons-Mariani/blob/main/research/vigilia.md"
  },
  {
    name: "Interaction Register",
    aliases: ["interaction register", "registre des interactions", "mail_trace", "mail trace", "registre d'interaction"],
    canonical_repo: "JeanHuguesRobert",
    canonical_rel: "interaction_packets/mail_trace.md",
    canonical_url: "https://github.com/JeanHuguesRobert/JeanHuguesRobert/blob/main/interaction_packets/mail_trace.md"
  },
  {
    name: "Exploration Rationnelle du Possible",
    aliases: ["exploration rationnelle du possible", "erp", "rational exploration of the possible"],
    canonical_repo: "barons-Mariani",
    canonical_rel: "research/potentics.md",
    canonical_url: "https://github.com/JeanHuguesRobert/barons-Mariani/blob/main/research/potentics.md"
  },
  {
    name: "Seconde Methode",
    aliases: ["seconde methode", "seconde méthode", "second method", "conserved negative returns"],
    canonical_repo: "cogentia",
    canonical_rel: "research/corpus_navigation_audit.md",
    canonical_url: "https://github.com/JeanHuguesRobert/cogentia/blob/main/research/corpus_navigation_audit.md"
  }
];

/**
 * S1 — Static Projection Generator
 * Generates llms.txt and updates per-repo AGENTS.md entry blocks.
 */
export function emitStaticProjection(ctx, inventory = []) {
  const rootDir = ctx.registryRoot || ctx.rootPath;
  const llmsPath = path.join(rootDir, "llms.txt");

  const lines = [
    "# Corpus Static Projection",
    "> Generated by cogentia.js (llms.txt standard). Authoritative registry map.",
    "",
    "## Repositories & Canonical Entry Points",
    ""
  ];

  for (const repo of ctx.repos || []) {
    lines.push(`- **[${repo.name}]**: ${repo.path}`);
    lines.push(`  - Role: ${repo.role || "primary"}`);
    lines.push(`  - Index: ${path.join(repo.path, "research", "index.md")}`);
    lines.push(`  - Concepts: ${path.join(repo.path, "research", "concepts.md")}`);
  }

  lines.push("");
  lines.push("## Key Seed Doctrines & Resolution Map");
  lines.push("");

  for (const item of SEED_CONCEPT_ALIASES) {
    lines.push(`- **${item.name}**: [${item.canonical_rel}](${item.canonical_url})`);
    lines.push(`  - Aliases: ${item.aliases.join(", ")}`);
  }

  lines.push("");
  lines.push("## Navigation Contract Verbs (CPsN v0.1)");
  lines.push("- `resolve(name)`: Deterministic alias -> canonical file lookup");
  lines.push("- `route(question, policy)`: Pre-filtered similarity routing across Attractor Cards");
  lines.push("- `fetch(card)`: Retrieve Attractor Card for source document");

  const content = lines.join("\n") + "\n";
  fs.writeFileSync(llmsPath, content, "utf8");

  // Also publish to profile repo if present
  const profileRepo = (ctx.repos || []).find(r => r.name === "JeanHuguesRobert");
  if (profileRepo && fs.existsSync(profileRepo.path)) {
    fs.writeFileSync(path.join(profileRepo.path, "llms.txt"), content, "utf8");
  }

  return { ok: true, llms_path: llmsPath, repos_projected: (ctx.repos || []).length };
}

/**
 * S2 — Publish Authoritative Registry
 */
export function publishRegistry(ctx) {
  const cogentiaRepo = (ctx.repos || []).find(r => r.name === "cogentia");
  const published = [];

  if (cogentiaRepo && fs.existsSync(cogentiaRepo.path)) {
    const target = path.join(cogentiaRepo.path, "docs", "registry.json");
    if (!fs.existsSync(path.dirname(target))) fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, JSON.stringify(ctx.config || ctx.repos, null, 2) + "\n", "utf8");
    published.push(target);
  }

  return { ok: true, published };
}

/**
 * S3 / Layer 1 — Deterministic Resolution (Name/Alias -> Canonical File)
 */
export function resolveConceptAlias(query, inventory = []) {
  const normQuery = String(query || "").toLowerCase().trim();
  if (!normQuery) return { hit: false };

  // 1. Check seed aliases first (S3)
  for (const seed of SEED_CONCEPT_ALIASES) {
    if (seed.name.toLowerCase() === normQuery || seed.aliases.some(a => normQuery.includes(a) || a.includes(normQuery))) {
      return {
        hit: true,
        resolution_kind: "seed_alias",
        name: seed.name,
        canonical_repo: seed.canonical_repo,
        canonical_rel: seed.canonical_rel,
        canonical_url: seed.canonical_url,
        confidence: 1.0,
      };
    }
  }

  // 2. Check inventory documents by title or basename match
  for (const doc of inventory) {
    const title = (doc.title || "").toLowerCase();
    const basename = path.basename(doc.rel || "", ".md").toLowerCase();
    if (title === normQuery || basename === normQuery) {
      return {
        hit: true,
        resolution_kind: "exact_document_match",
        name: doc.title || basename,
        canonical_repo: doc.repo,
        canonical_rel: doc.rel,
        canonical_url: doc.github_url || doc.url,
        confidence: 0.95,
      };
    }
  }

  return { hit: false };
}

/**
 * S4 — Attractor Card Generator
 */
export function buildAttractorCard(doc) {
  const title = doc.title || path.basename(doc.rel || "", ".md");
  return {
    card_id: `card:${doc.repo}:${doc.rel}`,
    what_i_hold: doc.description || title,
    questions_resolved: [
      `What is ${title}?`,
      `Where is ${title} defined?`
    ],
    claims_manifest: doc.github_url || doc.url || doc.rel,
    version: doc.version || "1.0",
    canonical_url: doc.github_url || doc.url || doc.rel,
    document_role: doc.document_role || "source",
    lifecycle_state: doc.lifecycle_state || "working",
  };
}

/**
 * S5 — Stub Convention Check
 */
export function isStubDocument(doc) {
  if (!doc) return false;
  if (doc.document_role === "stub") return true;
  if (doc.canonical || doc.canonical_url) return true;
  if (doc.size_bytes && doc.size_bytes < 500 && (doc.rel || "").indexOf("research/") < 0) return true;
  return false;
}

/**
 * S7 — 3-Layer Guide Routing Engine
 */
export function guideResolve(query, inventory = []) {
  // Layer 1: Deterministic resolution (No embeddings! Direct alias/canonical lookup)
  const layer1 = resolveConceptAlias(query, inventory);
  if (layer1.hit) {
    return {
      ok: true,
      layer: 1,
      mode: "deterministic_alias",
      query,
      result: layer1,
      canonical_url: layer1.canonical_url,
    };
  }

  // Layer 2: Hard Admissibility Pre-Filter
  const admissibleDocs = inventory.filter(doc => {
    if (isStubDocument(doc)) return false;
    if (doc.document_role && doc.document_role !== "source" && doc.document_role !== "operational") return false;
    if (doc.is_generated || (doc.rel || "").includes("index.md") || (doc.rel || "").includes("concepts.md")) return false;
    return true;
  });

  // Layer 3: Similarity & Reranking over Attractor Cards
  const queryWords = String(query).toLowerCase().split(/\s+/).filter(w => w.length > 2);
  const scored = admissibleDocs.map(doc => {
    const card = buildAttractorCard(doc);
    const text = `${doc.title || ''} ${doc.description || ''} ${doc.rel || ''}`.toLowerCase();
    let score = 0;
    for (const word of queryWords) {
      if (text.includes(word)) score += 1;
    }
    return { doc, card, score };
  }).filter(x => x.score > 0).sort((a, b) => b.score - a.score);

  if (scored.length > 0) {
    const top = scored[0];
    return {
      ok: true,
      layer: 3,
      mode: "attractor_card_similarity",
      query,
      result: top.card,
      canonical_url: top.card.canonical_url,
      scored_matches: scored.slice(0, 5).map(s => ({ title: s.doc.title, url: s.card.canonical_url, score: s.score })),
    };
  }

  return {
    ok: false,
    layer: 3,
    mode: "unresolved",
    query,
    message: "No canonical file or source document resolved in 1 hop.",
  };
}

/**
 * S6 — Navigation Benchmark & Negative-Returns Loop
 */
export function runNavigationBenchmark(ctx, inventory = []) {
  const seedQueries = [
    {
      query: "Where is Potentics?",
      expected_repo: "barons-Mariani",
      expected_rel: "research/potentics.md"
    },
    {
      query: "Where is the channel fragmentation document?",
      expected_repo: "barons-Mariani",
      expected_rel: "research/vigilia.md"
    },
    {
      query: "Where is the interaction register?",
      expected_repo: "JeanHuguesRobert",
      expected_rel: "interaction_packets/mail_trace.md"
    }
  ];

  const results = [];
  let passed = 0;

  for (const test of seedQueries) {
    const res = guideResolve(test.query, inventory);
    const actualRel = res.result?.canonical_rel || (res.result?.canonical_url || "").replace(/^.*github\.com\/[^\/]+\/[^\/]+\/blob\/[^\/]+\//, "");
    const isHit = res.ok && actualRel.includes(test.expected_rel.split("/").pop());

    if (isHit) {
      passed++;
      results.push({ query: test.query, status: "PASS", layer: res.layer, resolved: actualRel });
    } else {
      results.push({ query: test.query, status: "FAIL", layer: res.layer, expected: test.expected_rel, actual: actualRel });
    }
  }

  const report = {
    ok: passed === seedQueries.length,
    score: `${passed}/${seedQueries.length}`,
    total: seedQueries.length,
    passed,
    failed: seedQueries.length - passed,
    results,
  };

  // Save negative-returns log if any failed
  if (!report.ok) {
    const logPath = path.join(ctx.registryRoot || ctx.rootPath, ".cogentia-negative-returns.log");
    const logEntry = `[${new Date().toISOString()}] BENCHMARK FAIL: ${JSON.stringify(report)}\n`;
    fs.appendFileSync(logPath, logEntry, "utf8");
  }

  return report;
}
