// File: scripts/lib/privacy-views.js
// Description: Public vs private corpus view helpers for consolidation & projections.

/** Visibility levels aligned with cogentia.js VISIBILITY_LEVELS. */
export const PUBLIC_VIEW = "public";
export const PRIVATE_VIEW = "private";

/**
 * Default repo visibility when registry policy is missing.
 * Private / confidential / secret repos must never appear in public digests
 * or public llms.txt fan-out.
 */
export const DEFAULT_REPO_VISIBILITY = Object.freeze({
  "registre-mariani": Object.freeze({
    visibility: "private",
    public_presence: "hidden",
  }),
});

const NON_PUBLIC_LEVELS = new Set(["internal", "private", "confidential", "secret"]);

/**
 * Normalize a visibility string.
 * @param {unknown} value
 * @param {string} [fallback="public"]
 */
export function normalizeVisibility(value, fallback = PUBLIC_VIEW) {
  const clean = String(value || "").trim().toLowerCase();
  if (clean === "true") return "private";
  if (
    clean === "public" ||
    clean === "internal" ||
    clean === "private" ||
    clean === "confidential" ||
    clean === "secret"
  ) {
    return clean;
  }
  return fallback;
}

/**
 * Resolve visibility for a repo name or repo object.
 * Accepts { name, visibility?, privacy?, policy? }.
 */
export function repoVisibility(repoOrName) {
  if (typeof repoOrName === "string") {
    const def = DEFAULT_REPO_VISIBILITY[repoOrName];
    return normalizeVisibility(def?.visibility, PUBLIC_VIEW);
  }
  const name = repoOrName?.name || "";
  const fromPolicy =
    repoOrName?.policy?.visibility ||
    repoOrName?.policy?.privacy ||
    repoOrName?.visibility ||
    repoOrName?.privacy;
  if (fromPolicy != null && String(fromPolicy).trim() !== "") {
    return normalizeVisibility(fromPolicy, PUBLIC_VIEW);
  }
  const def = DEFAULT_REPO_VISIBILITY[name];
  return normalizeVisibility(def?.visibility, PUBLIC_VIEW);
}

/** True when the repo must stay out of public projections and digests. */
export function isPrivateRepo(repoOrName) {
  return NON_PUBLIC_LEVELS.has(repoVisibility(repoOrName));
}

/** True when the repo may appear in public artifacts. */
export function isPublicRepo(repoOrName) {
  return !isPrivateRepo(repoOrName);
}

/**
 * Filter a list of repos for a view.
 * @param {Array<{name: string}>} repos
 * @param {"public"|"private"} view
 */
export function filterReposForView(repos, view = PUBLIC_VIEW) {
  const list = Array.isArray(repos) ? repos : [];
  if (view === PRIVATE_VIEW) return list.slice();
  return list.filter((repo) => isPublicRepo(repo));
}

/**
 * Filter git log map { repoName: commits[] } for a view.
 * @param {Record<string, string[]>} gitLogs
 * @param {"public"|"private"} view
 */
export function filterGitLogsForView(gitLogs, view = PUBLIC_VIEW) {
  const entries = Object.entries(gitLogs || {});
  if (view === PRIVATE_VIEW) return entries;
  return entries.filter(([repoName]) => isPublicRepo(repoName));
}

/**
 * Detect cogentia-generated static projection files (safe to overwrite/remove).
 * @param {string} content
 */
export function isCogentiaGeneratedProjection(content) {
  return (
    typeof content === "string" &&
    content.includes("Generated by cogentia.js") &&
    (content.includes("llms.txt") || content.includes("llms-full.txt") || content.includes("Corpus Static Projection") || content.includes("Corpus Full Text Projection"))
  );
}

/**
 * Canonical monorepo inventory used by weekly consolidation.
 * Paths are relative to the cogentia registry root unless absolute.
 */
export function defaultMonorepoRepos(root = process.cwd()) {
  return [
    { name: "cogentia", path: ".", visibility: "public" },
    { name: "FractaVolta", path: "../FractaVolta", visibility: "public" },
    { name: "marenostrum", path: "../marenostrum", visibility: "public" },
    { name: "barons-Mariani", path: "../barons-Mariani", visibility: "public" },
    { name: "inseme", path: "../inseme", visibility: "public" },
    { name: "Inox", path: "../Inox", visibility: "public" },
    {
      name: "registre-mariani",
      path: "../registre-mariani",
      visibility: "private",
      public_presence: "hidden",
    },
    { name: "ubikia", path: "../ubikia", visibility: "public" },
    { name: "JeanHuguesRobert", path: "../JeanHuguesRobert", visibility: "public" },
    { name: "StructEnv", path: "../StructEnv", visibility: "public" },
  ].map((repo) => ({
    ...repo,
    // Absolute path helpers for consolidation scans
    absPath: repo.path === "." ? root : undefined,
  }));
}
