#!/usr/bin/env node
/*
 * cogentia.js v2
 *
 * Design rule:
 *   plan  = read-only, complete, machine-readable
 *   apply = writes exactly the planned generated views
 *   verify = post-action health check
 *
 * This is a deliberate interface break. The previous implementation is kept as
 * scripts/cogentia.v1-history.js for historical inspection only.
 */

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { createHash, randomBytes } from "node:crypto";

const VERSION = "2.1.0";
const CONFIG_FILE = ".cogentia.json";
const DOCUMENTS_FILE = "documents.md";
const CORPUS_STATUS_FILE = "corpus-status.md";
const CONCEPTS_FILE = "concepts.md";
const INDEX_FILE = "index.md";
const GENERATED_NOTE = "Generated by `cogentia.js v2`.";
const CONTINUATION_PROTOCOL = "cogentia.continuation.v2";
const MAINTENANCE_RE = /\b(refresh|generated|auto|backlinks?|trails?|readme|documents|corpus|navigation|frontmatter|stamp|bulk|maintenance)\b/i;
const BUILTIN_IGNORED_BASENAMES = new Set([
  "README.md",
  "LICENSE",
  "LICENSE.md",
  "TODO.md",
  "CHANGELOG.md",
  "CHANGES.md",
  "CONTRIBUTING.md",
  "CODE_OF_CONDUCT.md",
]);
const BUILTIN_SKIP_DIRS = new Set([
  ".git",
  "node_modules",
  ".turbo",
  "dist",
  "build",
  ".cache",
  ".next",
  ".vite",
  "coverage",
]);
const DEFAULT_REPO_POLICIES = {
  inseme: {
    default_scope: "research",
    note: "local policy: unstable outside research",
  },
  JeanHuguesRobert: {
    ignore_dirty: [".cogentia/**"],
    role: "registry",
  },
};

const argv = process.argv.slice(2);
const JSON_MODE = takeFlag("--json");
const command = argv.shift() || "help";

main().catch(err => {
  if (JSON_MODE) {
    console.error(JSON.stringify({ ok: false, error: err.message, stack: err.stack }, null, 2));
  } else {
    console.error(`cogentia: ${err.message}`);
  }
  process.exit(1);
});

async function main() {
  switch (command) {
    case "help":
    case "-h":
    case "--help":
      return cmdHelp();
    case "version":
    case "--version":
      return output({ version: VERSION }, `cogentia.js v${VERSION}`);
    case "state":
      return cmdState();
    case "status":
      return cmdStatus();
    case "corpus":
      return cmdCorpus(argv.shift() || "plan");
    case "docs":
    case "documents":
      return cmdDocs(argv.shift() || "summary");
    case "concepts":
      return cmdConcepts(argv.shift() || "check");
    case "continuation":
      return cmdContinuation(argv.shift() || "list");
    case "git":
      return cmdGit(argv.shift() || "verify");
    default:
      throw new Error(`Unknown command "${command}". Run: node scripts/cogentia.js help`);
  }
}

function cmdHelp() {
  const text = `
cogentia.js v${VERSION}

Usage:
  node scripts/cogentia.js <command> [args] [--json]

Core commands:
  corpus plan              Read-only plan of generated navigation changes.
  corpus apply             Apply generated navigation changes from a fresh plan.
  corpus verify            Verify generated views, gaps and git drift.
  status                   Local health table used by the git hook.

Document commands:
  docs summary             Numeric corpus summaries.
  docs query [repo|all]    Query documents. Flags: --not-indexed --role <r> --q <text>
                           --sort updated|created|size|links --limit <n> --include-ignored
  docs search <text>       Full-text search over active markdown documents.
                           Flags: --repo <name> --limit <n> --include-generated
  docs gaps                Documents not referenced by their repo research/index.md.
  docs inspect <repo/path.md>
  docs judgments [repo|all]
                           List document-role cases requiring external judgment.
                           Add --emit-continuations to create judgment requests.

Concept commands:
  concepts list [repo|all]
  concepts check [repo|all]

Continuation commands:
  continuation emit        Emit an external judgment request.
  continuation list        List continuations. Flags: --status active|resolved|cancelled|all
  continuation inspect <id>
  continuation resolve <id> [result.json] --decision <text> --reason <text>
  continuation resume <id> [result.json]   Alias for resolve.
  continuation cancel <id> --reason <text>
  continuation schema

Git:
  git verify               Ahead/behind and dirty state for all repos.

Plan/apply flags:
  --scope configured|all|research|repo:<name>
  --repo <name>            Equivalent to --scope repo:<name>
  --no-backlinks           Skip backlink blocks.
  --no-documents           Skip registry research/documents.md.
  --no-corpus-status       Skip per-repo research/corpus-status.md.
  --create-backlinks       Create missing backlink blocks in linked markdown files.
  --include-content        Include before/after bodies in JSON plans.
  --strict                 Non-zero exit when verify finds issues.

Registry:
  Uses --registry <path>, COGENTIA_REGISTRY, nearest .cogentia.json, or
  C:/tweesic/JeanHuguesRobert/.cogentia.json.
`;
  console.log(text.trimStart());
}

function cmdState() {
  const ctx = loadContext();
  const repos = ctx.repos.map(repo => ({
    name: repo.name,
    path: repo.path,
    branch: repo.branch,
    exists: fs.existsSync(repo.path),
    policy: repo.policy,
    index: fileExists(repo.path, "research", INDEX_FILE),
    concepts: fileExists(repo.path, "research", CONCEPTS_FILE),
    corpus_status: fileExists(repo.path, "research", CORPUS_STATUS_FILE),
  }));
  output({ ok: true, version: VERSION, registry: ctx.configPath, repos }, formatState(repos));
}

function cmdStatus() {
  const ctx = loadContext();
  const inventory = buildInventory(ctx);
  const git = verifyGit(ctx);
  const rows = ctx.repos.map(repo => {
    const docs = inventory.documents.filter(d => d.repo === repo.name && !d.index.ignored);
    const unindexed = docs.filter(isIndexGap).length;
    const g = git.find(x => x.repo === repo.name);
    return {
      repo: repo.name,
      branch: repo.branch,
      docs: docs.length,
      unindexed,
      dirty: g.dirty_count,
      ahead: g.ahead,
      behind: g.behind,
    };
  });
  if (JSON_MODE) return output({ ok: true, rows });
  console.log("\nCorpus status\n");
  console.log(`${pad("Repository", 18)} ${pad("Branch", 8)} ${pad("Docs", 6, true)} ${pad("Gaps", 6, true)} ${pad("Dirty", 6, true)} Drift`);
  console.log("-".repeat(70));
  for (const r of rows) {
    const drift = r.behind || r.ahead ? `${r.behind} behind / ${r.ahead} ahead` : "ok";
    console.log(`${pad(r.repo, 18)} ${pad(r.branch, 8)} ${pad(r.docs, 6, true)} ${pad(r.unindexed, 6, true)} ${pad(r.dirty, 6, true)} ${drift}`);
  }
}

function cmdCorpus(sub) {
  switch (sub) {
    case "plan":
      return cmdCorpusPlan();
    case "apply":
      return cmdCorpusApply();
    case "verify":
      return cmdCorpusVerify();
    default:
      throw new Error(`Unknown corpus subcommand "${sub}". Use plan, apply, or verify.`);
  }
}

function cmdCorpusPlan() {
  const ctx = loadContext();
  const options = planOptions();
  const plan = buildPlan(ctx, options);
  const printable = displayPlan(plan, options);
  output(printable, formatPlan(printable));
}

function cmdCorpusApply() {
  const ctx = loadContext();
  const options = planOptions();
  const plan = buildPlan(ctx, options);
  for (const change of plan.changes) {
    if (!change.allowed) continue;
    ensureDir(path.dirname(change.full_path));
    fs.writeFileSync(change.full_path, change.after, "utf8");
  }
  const result = {
    ok: true,
    applied: plan.changes.filter(c => c.allowed).map(stripChangeBody),
    skipped: plan.changes.filter(c => !c.allowed).map(stripChangeBody),
    summary: plan.summary,
  };
  output(result, formatApply(result));
}

function cmdCorpusVerify() {
  const ctx = loadContext();
  const strict = hasFlag("--strict");
  const plan = buildPlan(ctx, { ...planOptions(), quiet: true });
  const inventory = buildInventory(ctx);
  const git = verifyGit(ctx);
  const gaps = inventory.documents.filter(isIndexGap);
  const issues = [];
  if (plan.changes.length) issues.push(`${plan.changes.length} generated view(s) stale`);
  if (gaps.length) issues.push(`${gaps.length} document(s) not indexed`);
  for (const g of git) {
    if (g.behind) issues.push(`${g.repo} behind upstream`);
    if (g.ahead) issues.push(`${g.repo} ahead upstream`);
  }
  const result = {
    ok: issues.length === 0,
    issues,
    stale_views: plan.changes.map(stripChangeBody),
    gaps: gaps.map(sanitizeDoc),
    git,
  };
  if (JSON_MODE) {
    console.log(JSON.stringify(result, null, 2));
  } else {
    console.log("\nCorpus verify\n");
    if (!issues.length) console.log("ok");
    else for (const issue of issues) console.log(`- ${issue}`);
  }
  if (strict && issues.length) process.exit(2);
}

function cmdDocs(sub) {
  const ctx = loadContext();
  const inventory = buildInventory(ctx);
  switch (sub) {
    case "summary":
      return output(docSummary(inventory), formatDocSummary(docSummary(inventory)));
    case "query":
      return cmdDocsQuery(inventory, optionalPositional("all"));
    case "search":
      return cmdDocsSearch(inventory);
    case "gaps":
      return cmdDocsGaps(inventory);
    case "inspect":
      return cmdDocsInspect(inventory, argv.shift());
    case "judgments":
      return cmdDocsJudgments(ctx, inventory, optionalPositional("all"));
    default:
      throw new Error(`Unknown docs subcommand "${sub}". Use summary, query, search, gaps, inspect, or judgments.`);
  }
}

function cmdDocsQuery(inventory, repoArg) {
  const filter = docsFilter(repoArg);
  const docs = filterDocuments(inventory.documents, filter).map(sanitizeDoc);
  output({ ok: true, filter, count: docs.length, documents: docs }, formatDocs(docs));
}

function cmdDocsSearch(inventory) {
  const repo = valueFlag("--repo") || "all";
  const limit = Number(valueFlag("--limit") || 25) || 25;
  const includeGenerated = takeFlag("--include-generated");
  const q = valueFlag("--q") || argv.join(" ").trim();
  if (!q) throw new Error("Usage: docs search <text> [--repo <name>] [--limit <n>]");
  const needle = q.toLowerCase();
  const docs = inventory.documents
    .filter(d => !d.index.ignored)
    .filter(d => includeGenerated || !isGeneratedNavigationDoc(d))
    .filter(d => repo === "all" || d.repo === repo)
    .sort(compareDocs("repo"));
  const matches = [];
  for (const doc of docs) {
    const lines = readFileIfExists(doc.full_path).split(/\r?\n/);
    for (let i = 0; i < lines.length; i++) {
      if (!lines[i].toLowerCase().includes(needle)) continue;
      matches.push({
        repo: doc.repo,
        path: doc.rel,
        title: doc.title,
        line: i + 1,
        snippet: snippet(lines, i),
        github_url: `${doc.github_url}#L${i + 1}`,
      });
      if (matches.length >= limit) break;
    }
    if (matches.length >= limit) break;
  }
  output({ ok: true, query: q, repo, include_generated: includeGenerated, count: matches.length, matches }, formatSearch(matches, q));
}

function cmdDocsGaps(inventory) {
  const docs = inventory.documents
    .filter(isIndexGap)
    .sort(compareDocs("repo"))
    .map(sanitizeDoc);
  output({ ok: true, count: docs.length, documents: docs }, formatDocs(docs));
}

function cmdDocsInspect(inventory, ref) {
  if (!ref) throw new Error("Usage: docs inspect <repo/path.md>");
  const doc = resolveDocRef(inventory, ref);
  if (!doc) throw new Error(`Document not found: ${ref}`);
  output({ ok: true, document: sanitizeDoc(doc) }, formatDoc(doc));
}

function cmdDocsJudgments(ctx, inventory, repoArg) {
  const emit = takeFlag("--emit-continuations");
  const includeInferredSource = takeFlag("--include-inferred-source");
  const requests = documentJudgmentRequests(inventory, repoArg, { includeInferredSource });
  const continuations = emit
    ? requests.map(req => emitContinuation(ctx, req))
    : [];
  const result = {
    ok: true,
    count: requests.length,
    emitted: continuations.filter(x => x.created).length,
    existing: continuations.filter(x => !x.created).length,
    include_inferred_source: includeInferredSource,
    needs_judgment: requests,
    continuations: continuations.map(x => stripContinuationBody(x.continuation)),
  };
  output(result, formatJudgments(result));
}

function cmdConcepts(sub) {
  const ctx = loadContext();
  const repoArg = argv.shift() || "all";
  const concepts = loadConcepts(ctx);
  const selected = repoArg === "all" ? concepts : concepts.filter(r => r.repo === repoArg);
  if (!selected.length && repoArg !== "all") throw new Error(`Unknown repo or no concepts: ${repoArg}`);
  switch (sub) {
    case "list":
      return output({ ok: true, repos: selected }, formatConceptList(selected));
    case "check":
      return output({ ok: true, results: checkConcepts(selected, concepts) }, formatConceptCheck(checkConcepts(selected, concepts)));
    default:
      throw new Error(`Unknown concepts subcommand "${sub}". Use list or check.`);
  }
}

function cmdGit(sub) {
  if (sub !== "verify") throw new Error(`Unknown git subcommand "${sub}". Use verify.`);
  const ctx = loadContext();
  const result = verifyGit(ctx);
  output({ ok: true, repos: result }, formatGit(result));
}

function cmdContinuation(sub) {
  const ctx = loadContext();
  switch (sub) {
    case "emit":
      return cmdContinuationEmit(ctx);
    case "list":
    case "queue":
      return cmdContinuationList(ctx);
    case "inspect":
      return cmdContinuationInspect(ctx, argv.shift());
    case "resolve":
    case "resume":
      return cmdContinuationResolve(ctx, argv.shift());
    case "cancel":
    case "abort":
      return cmdContinuationCancel(ctx, argv.shift());
    case "schema":
      return output(continuationSchema(), formatContinuationSchema());
    default:
      throw new Error(`Unknown continuation subcommand "${sub}". Use emit, list, inspect, resolve, cancel, or schema.`);
  }
}

function cmdContinuationEmit(ctx) {
  const kind = valueFlag("--kind") || "judgment";
  const title = valueFlag("--title") || "";
  const repo = valueFlag("--repo");
  const docPath = valueFlag("--path") || valueFlag("--file");
  const dedupeKey = valueFlag("--dedupe-key") || "";
  const priority = Number(valueFlag("--priority") || 0) || 0;
  const context = readContinuationContext();
  const question = valueFlag("--question") || argv.join(" ").trim();
  if (!question) throw new Error("Usage: continuation emit --question <text> [--kind <kind>] [--title <title>]");
  const result = emitContinuation(ctx, {
    kind,
    title: title || kind,
    question,
    priority,
    dedupe_key: dedupeKey,
    subject: { repo: repo || "", path: docPath || "" },
    context,
  });
  output(result, formatContinuationEmit(result));
}

function cmdContinuationList(ctx) {
  const status = valueFlag("--status") || "active";
  const kind = valueFlag("--kind") || "";
  const continuations = loadContinuations(ctx)
    .filter(c => status === "all" || c.status === status)
    .filter(c => !kind || c.kind === kind)
    .sort(compareContinuations);
  output({ ok: true, store: continuationsDir(ctx), status, kind: kind || "all", continuations: continuations.map(stripContinuationBody) }, formatContinuationList(continuations, status));
}

function cmdContinuationInspect(ctx, id) {
  if (!id) throw new Error("Usage: continuation inspect <id>");
  const continuation = loadContinuation(ctx, id);
  output({ ok: true, continuation }, formatContinuationInspect(continuation));
}

function cmdContinuationResolve(ctx, id) {
  if (!id) throw new Error("Usage: continuation resolve <id> [result.json] --decision <text> --reason <text>");
  const continuation = loadContinuation(ctx, id);
  if (continuation.status !== "active") throw new Error(`Continuation ${id} is not active (status=${continuation.status}).`);
  const payload = readContinuationPayload();
  if (payload.continuation_id && payload.continuation_id !== id) {
    throw new Error(`continuation_id mismatch: got ${payload.continuation_id}, expected ${id}`);
  }
  const decision = valueFlag("--decision") || payload.decision || payload.chosen_alternative || payload.status || "";
  const reason = valueFlag("--reason") || payload.reason || payload.summary || "";
  if (!decision && !Object.keys(payload).length) throw new Error("Resolve requires --decision <text> or a result JSON file.");
  const now = new Date().toISOString();
  continuation.status = "resolved";
  continuation.updated_at = now;
  continuation.resolution = {
    resolved_at: now,
    decision,
    reason,
    payload,
  };
  continuation.history.push({ at: now, event: "resolved", decision, reason });
  saveContinuation(ctx, continuation);
  output({ ok: true, continuation: stripContinuationBody(continuation) }, formatContinuationResolved(continuation));
}

function cmdContinuationCancel(ctx, id) {
  if (!id) throw new Error("Usage: continuation cancel <id> --reason <text>");
  const continuation = loadContinuation(ctx, id);
  if (continuation.status !== "active") throw new Error(`Continuation ${id} is not active (status=${continuation.status}).`);
  const reason = valueFlag("--reason") || argv.join(" ").trim();
  if (!reason) throw new Error("Cancel requires --reason <text>.");
  const now = new Date().toISOString();
  continuation.status = "cancelled";
  continuation.updated_at = now;
  continuation.resolution = {
    cancelled_at: now,
    reason,
  };
  continuation.history.push({ at: now, event: "cancelled", reason });
  saveContinuation(ctx, continuation);
  output({ ok: true, continuation: stripContinuationBody(continuation) }, formatContinuationResolved(continuation));
}

function buildPlan(ctx, options) {
  const inventory = buildInventory(ctx);
  const changes = [];
  if (options.corpusStatus) {
    for (const repo of ctx.repos) {
      if (!repoSelected(repo, options)) continue;
      const full = path.join(repo.path, "research", CORPUS_STATUS_FILE);
      const before = readFileIfExists(full);
      const after = renderCorpusStatus(repo, ctx, inventory, before);
      addChange(changes, repo, full, "corpus-status", before, after, true, "refresh structural status blocks");
    }
  }
  if (options.documents) {
    const registryRepo = ctx.repos.find(r => r.name === "JeanHuguesRobert") || ctx.repos[ctx.repos.length - 1];
    if (registryRepo && repoSelected(registryRepo, options)) {
      const full = path.join(registryRepo.path, "research", DOCUMENTS_FILE);
      const before = readFileIfExists(full);
      const after = renderDocuments(inventory, ctx);
      addChange(changes, registryRepo, full, "documents", before, after, true, "refresh consolidated document catalog");
    }
  }
  if (options.backlinks) {
    const backlinkChanges = planBacklinks(ctx, inventory, options);
    for (const change of backlinkChanges) changes.push(change);
  }
  const clean = changes.filter(c => c.before !== c.after);
  return {
    ok: true,
    version: VERSION,
    registry: ctx.configPath,
    options,
    summary: summarizePlan(clean, inventory),
    changes: clean,
  };
}

function displayPlan(plan, options) {
  const includeContent = options.includeContent || false;
  return {
    ...plan,
    changes: plan.changes.map(change => includeContent ? change : stripChangeBody(change)),
  };
}

function addChange(changes, repo, full, type, before, after, allowed, reason) {
  if (before === after) return;
  changes.push({
    repo: repo.name,
    path: rel(repo.path, full),
    full_path: full,
    type,
    action: before === "" ? "create" : "update",
    allowed,
    reason,
    before_hash: sha(before),
    after_hash: sha(after),
    bytes_delta: Buffer.byteLength(after) - Buffer.byteLength(before),
    before,
    after,
  });
}

function planOptions() {
  const repo = valueFlag("--repo");
  const scope = repo ? `repo:${repo}` : (valueFlag("--scope") || "configured");
  return {
    scope,
    backlinks: !hasFlag("--no-backlinks"),
    corpusStatus: !hasFlag("--no-corpus-status"),
    documents: !hasFlag("--no-documents"),
    createBacklinks: hasFlag("--create-backlinks"),
    includeContent: hasFlag("--include-content"),
  };
}

function buildInventory(ctx) {
  const repoMetas = new Map();
  const documents = [];
  for (const repo of ctx.repos) {
    const ignore = loadIgnore(repo.path);
    const indexSets = buildIndexSets(repo);
    const gitIndex = buildGitDateIndex(repo);
    repoMetas.set(repo.name, { ignore, indexSets });
    for (const file of listMarkdown(repo.path)) {
      const relPath = rel(repo.path, file);
      const policyExcluded = repo.policy.default_scope === "research" && !relPath.startsWith("research/");
      const ignored = matchesIgnore(relPath, ignore) || policyExcluded;
      const raw = fs.readFileSync(file, "utf8");
      const fm = parseFrontmatter(raw);
      const title = extractTitle(raw, file, fm.data);
      const dates = gitDates(gitIndex, relPath);
      const role = classifyRole(repo, relPath, file, fm.data, ignored, indexSets);
      documents.push({
        repo: repo.name,
        repo_path: repo.path,
        branch: repo.branch,
        full_path: file,
        rel: relPath,
        github_url: githubUrl(repo, relPath),
        title,
        role: role.role,
        role_source: role.source,
        role_confidence: role.confidence,
        frontmatter: fm.data,
        size: {
          bytes: Buffer.byteLength(raw),
          body_bytes: Buffer.byteLength(fm.body),
          words: wordCount(fm.body),
          headings: countHeadings(fm.body),
          reading_minutes: Math.max(1, Math.ceil(wordCount(fm.body) / 220)),
        },
        created: dates.created,
        updated: dates.updated,
        links: { out_internal: 0, out_cross_repo: 0, in_internal: 0, in_cross_repo: 0 },
        index: {
          ignored,
          ignored_reason: policyExcluded ? "policy:default_scope=research" : (matchesIgnore(relPath, ignore) ? "ignore" : ""),
          referenced: indexSets.all.has(path.resolve(file)) || relPath === "research/index.md",
          published: indexSets.published.has(path.resolve(file)),
        },
      });
    }
  }
  const byFull = new Map(documents.map(d => [path.resolve(d.full_path), d]));
  const edges = [];
  for (const doc of documents) {
    const raw = fs.readFileSync(doc.full_path, "utf8");
    for (const link of extractMarkdownLinks(raw)) {
      const target = resolveMarkdownLink(ctx, doc, link.url);
      if (!target) continue;
      const targetDoc = byFull.get(path.resolve(target.full_path));
      if (!targetDoc) continue;
      edges.push({ from: doc.full_path, to: targetDoc.full_path, from_repo: doc.repo, to_repo: targetDoc.repo, url: link.url });
      if (targetDoc.repo === doc.repo) {
        doc.links.out_internal++;
        targetDoc.links.in_internal++;
      } else {
        doc.links.out_cross_repo++;
        targetDoc.links.in_cross_repo++;
      }
    }
  }
  const coupling = summarizeCoupling(edges);
  return { timestamp: new Date().toISOString(), documents, edges, coupling, repoMetas };
}

function classifyRole(repo, relPath, full, fm, ignored, indexSets) {
  const r = relPath.replace(/\\/g, "/");
  const explicit = String(fm.document_role || fm.role || "").toLowerCase();
  const derivedFrom = fm.derived_from || fm.derived_by;
  if (ignored) return { role: "archive", source: "ignore", confidence: "strong" };
  if (/^research\/(index|concepts|corpus-status|documents)\.md$/i.test(r)) {
    return { role: "index", source: "path:research", confidence: "strong" };
  }
  if (/\balias\b/.test(explicit) || fm.redirect_to || /^see\s+/i.test(readFileIfExists(full).trim())) {
    return { role: "alias", source: "frontmatter/path", confidence: "medium" };
  }
  if (explicit.includes("symmetric") || explicit.includes("souverain")) {
    return { role: "source", source: "frontmatter:document_role", confidence: "strong" };
  }
  if (derivedFrom || explicit.includes("derived") || r.includes("/derived_products/")) {
    return { role: "derived", source: "frontmatter/path:derived", confidence: "strong" };
  }
  if (indexSets.published.has(path.resolve(full))) {
    return { role: "source", source: "research/index.md:Published", confidence: "strong" };
  }
  if (r.startsWith("research/trails/")) return { role: "trail", source: "path:research/trails", confidence: "strong" };
  if (r.startsWith("research/")) return { role: "source", source: "path:research", confidence: "medium" };
  if (r.startsWith("trace/docs/") || r.startsWith("docs/") || r.startsWith("interaction_packets/") || r.startsWith("prompts/")) {
    return { role: "operational", source: "path:operational", confidence: "strong" };
  }
  return { role: "unknown", source: "fallback", confidence: "weak" };
}

function renderCorpusStatus(repo, ctx, inventory, before) {
  const original = before || bootstrapCorpusStatus(repo);
  let content = original;
  content = replaceSection(content, "registered_repos", renderRegisteredRepos(ctx));
  content = replaceSection(content, "graph", renderRepoGraph(inventory, ctx));
  content = replaceSection(content, "concepts", renderConceptSummary(repo, loadConcepts(ctx)));
  content = replaceSection(content, "concept_graph", renderConceptGraph(loadConcepts(ctx), ctx));
  content = replaceSection(content, "published", renderPublishedBlock(repo));
  content = replaceSection(content, "possibilities", renderPossibilitiesBlock(repo));
  return ensureFinalNewline(content);
}

function bootstrapCorpusStatus(repo) {
  return `---\ntitle: "Corpus Status - ${repo.name}"\ndate: ${today()}\n---\n\n# Corpus Status - ${repo.name}\n\n## Registered Repositories\n\n<!-- BEGIN_AUTO: registered_repos -->\n<!-- END_AUTO: registered_repos -->\n\n---\n\n## Cross-Reference Graph\n\n<!-- BEGIN_AUTO: graph -->\n<!-- END_AUTO: graph -->\n\n---\n\n## Concepts\n\n<!-- BEGIN_AUTO: concepts -->\n<!-- END_AUTO: concepts -->\n\n## Concept Graph\n\n<!-- BEGIN_AUTO: concept_graph -->\n<!-- END_AUTO: concept_graph -->\n\n---\n\n## Published\n\n<!-- BEGIN_AUTO: published -->\n<!-- END_AUTO: published -->\n\n---\n\n## What Is Proved\n\n_Manually curated._\n\n## Open Objections\n\n_Manually curated._\n\n## What Remains Possible\n\n<!-- BEGIN_AUTO: possibilities -->\n<!-- END_AUTO: possibilities -->\n\n`;
}

function renderRegisteredRepos(ctx) {
  const lines = [
    "| Repository | research/index.md | Branch | Policy |",
    "|---|---|---|---|",
  ];
  for (const repo of ctx.repos) {
    const hasIndex = fileExists(repo.path, "research", INDEX_FILE) ? "yes" : "no";
    lines.push(`| ${repo.name} | ${hasIndex} | ${repo.branch} | ${repo.policy.default_scope || "all"} |`);
  }
  return lines.join("\n");
}

function renderRepoGraph(inventory, ctx) {
  const edges = inventory.coupling.repo_edges.filter(e => e.weight > 0);
  const lines = ["```mermaid", "graph LR"];
  for (const repo of ctx.repos) lines.push(`  ${mermaidId(repo.name)}["${escapeMermaid(repo.name)}"]`);
  for (const e of edges) lines.push(`  ${mermaidId(e.from)} -->|${e.weight}| ${mermaidId(e.to)}`);
  lines.push("```");
  if (!edges.length) lines.push("\n*(No cross-repo links detected.)*");
  return lines.join("\n");
}

function renderPublishedBlock(repo) {
  const index = path.join(repo.path, "research", INDEX_FILE);
  if (!fs.existsSync(index)) return "*(No research/index.md found.)*";
  const section = extractHeadingSection(fs.readFileSync(index, "utf8"), "Published");
  const rows = section.split(/\r?\n/).filter(line => /^\|.+\|$/.test(line.trim()));
  if (rows.length >= 2) return rows.join("\n");
  return "*(No Published table found.)*";
}

function renderPossibilitiesBlock(repo) {
  const index = path.join(repo.path, "research", INDEX_FILE);
  if (!fs.existsSync(index)) return "*(No research/index.md found.)*";
  const section = extractHeadingSection(fs.readFileSync(index, "utf8"), "Open Possibilities");
  const bullets = section.split(/\r?\n/).filter(line => /^\s*-\s+/.test(line));
  return bullets.length ? bullets.join("\n") : "*(No open possibilities listed.)*";
}

function renderDocuments(inventory, ctx) {
  const docs = inventory.documents.filter(d => !d.index.ignored);
  const byRepo = groupBy(docs, d => d.repo);
  const gaps = docs.filter(isIndexGap);
  const recent = [...docs].sort(compareDocs("updated")).slice(0, 80);
  const sources = docs.filter(d => d.role === "source").sort(compareDocs("repo"));
  const lines = [];
  lines.push("---");
  lines.push('title: "Documents - All Tracked Repos"');
  lines.push(`last_modified_at: ${today()}`);
  lines.push("---");
  lines.push("");
  lines.push("# Documents - All Tracked Repos");
  lines.push("");
  lines.push(`_${GENERATED_NOTE} Registry: \`${ctx.configPath}\`._`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("|---|---:|");
  lines.push(`| Repositories | ${ctx.repos.length} |`);
  lines.push(`| Documents | ${docs.length} |`);
  lines.push(`| Source documents | ${sources.length} |`);
  lines.push(`| Unindexed documents | ${gaps.length} |`);
  lines.push("");
  lines.push("## Per Repository");
  lines.push("");
  lines.push("| Repository | Documents | Source | Derived | Operational | Gaps |");
  lines.push("|---|---:|---:|---:|---:|---:|");
  for (const repo of ctx.repos) {
    const list = byRepo.get(repo.name) || [];
    lines.push(`| ${repo.name} | ${list.length} | ${list.filter(d => d.role === "source").length} | ${list.filter(d => d.role === "derived").length} | ${list.filter(d => d.role === "operational").length} | ${list.filter(isIndexGap).length} |`);
  }
  lines.push("");
  lines.push("## Recent Activity");
  lines.push("");
  lines.push(renderDocTable(recent));
  lines.push("");
  lines.push("## Source Documents");
  lines.push("");
  lines.push(renderDocTable(sources));
  lines.push("");
  lines.push("## Index Gaps");
  lines.push("");
  lines.push(gaps.length ? renderDocTable(gaps.sort(compareDocs("repo"))) : "No unindexed documents.");
  lines.push("");
  return lines.join("\n");
}

function renderDocTable(docs) {
  const lines = ["| Title | Repo | Role | Updated | Created | Local |", "|---|---|---|---|---|---|"];
  for (const d of docs) {
    lines.push(`| [${escapeTable(d.title)}](${d.github_url || "#"}) | ${d.repo} | ${d.role} | ${d.updated.date || "-"} | ${d.created.date || "-"} | \`${d.rel}\` |`);
  }
  return lines.join("\n");
}

function planBacklinks(ctx, inventory, options) {
  const byTarget = new Map();
  for (const edge of inventory.edges) {
    if (!byTarget.has(edge.to)) byTarget.set(edge.to, []);
    byTarget.get(edge.to).push(edge.from);
  }
  const docsByFull = new Map(inventory.documents.map(d => [path.resolve(d.full_path), d]));
  const changes = [];
  for (const [targetFull, sourceFulls] of byTarget.entries()) {
    const target = docsByFull.get(path.resolve(targetFull));
    if (!target) continue;
    const repo = ctx.repos.find(r => r.name === target.repo);
    if (!repo || !repoSelected(repo, options)) continue;
    const allowed = pathAllowedByScope(repo, target.rel, options);
    if (!allowed) continue;
    const before = readFileIfExists(targetFull);
    const hasBlock = before.includes("<!-- BEGIN_AUTO: backlinks -->");
    if (!hasBlock && !options.createBacklinks) continue;
    const sourceDocs = sourceFulls.map(f => docsByFull.get(path.resolve(f))).filter(Boolean);
    const block = renderBacklinkBlock(repo, target, sourceDocs);
    const after = hasBlock
      ? replaceSection(before, "backlinks", block)
      : ensureFinalNewline(before) + `\n<!-- BEGIN_AUTO: backlinks -->\n${block}\n<!-- END_AUTO: backlinks -->\n`;
    addChange(changes, repo, targetFull, "backlinks", before, after, true, "refresh backlink block");
  }
  return changes;
}

function renderBacklinkBlock(repo, target, sourceDocs) {
  const unique = [...new Map(sourceDocs.map(d => [d.full_path, d])).values()]
    .sort((a, b) => a.repo.localeCompare(b.repo) || a.title.localeCompare(b.title));
  const lines = ["### Backlinks", "", "*These documents link to this file:*"];
  for (const source of unique) {
    const href = source.repo === target.repo
      ? rel(path.dirname(target.full_path), source.full_path)
      : source.github_url;
    lines.push(`- [${source.title}](${href})`);
  }
  return lines.join("\n");
}

function loadConcepts(ctx) {
  return ctx.repos.map(repo => {
    const full = path.join(repo.path, "research", CONCEPTS_FILE);
    if (!fs.existsSync(full)) return { repo: repo.name, path: full, ok: false, concepts: [], reason: "missing" };
    const raw = fs.readFileSync(full, "utf8");
    return { repo: repo.name, path: full, ok: true, concepts: parseConcepts(raw, repo) };
  });
}

function parseConcepts(raw, repo) {
  const parts = stripAutoSections(raw).split(/^##\s+/m);
  parts.shift();
  const concepts = [];
  for (const part of parts) {
    const lines = part.split(/\r?\n/);
    const name = lines.shift().trim().replace(/\s+#.*$/, "");
    if (!name || isNonConceptHeading(name)) continue;
    const body = lines.join("\n");
    concepts.push({
      name,
      slug: slug(name),
      repo: repo.name,
      type: field(body, "Type"),
      scope: field(body, "Scope"),
      status: field(body, "Status"),
      short_definition: field(body, "Short definition"),
      parents: listAfter(body, "Parent concepts"),
      children: listAfter(body, "Child concepts"),
      related: listAfter(body, "Related concepts"),
      documents: [...listAfter(body, "Reference documents"), ...listAfter(body, "Used in")],
    });
  }
  return concepts;
}

function isNonConceptHeading(name) {
  const key = String(name).toLowerCase().trim();
  return new Set([
    "status scale",
    "registered repositories",
    "cross-reference graph",
    "concept graph",
    "published",
    "what is proved",
    "open objections",
    "what remains possible",
    "summary",
    "per repository",
    "recent activity",
    "source documents",
    "index gaps",
  ]).has(key);
}

function renderConceptSummary(repo, loaded) {
  const r = loaded.find(x => x.repo === repo.name);
  if (!r || !r.ok || !r.concepts.length) return "*(No concepts registered.)*";
  const lines = ["| Concept | Scope | Status | Type |", "|---|---|---|---|"];
  for (const c of r.concepts) {
    lines.push(`| [${escapeTable(c.name)}](./concepts.md#${c.slug}) | ${escapeTable(c.scope || "-")} | ${escapeTable(c.status || "-")} | ${escapeTable(c.type || "-")} |`);
  }
  return lines.join("\n");
}

function renderConceptGraph(loaded, ctx) {
  const all = loaded.flatMap(r => r.concepts);
  if (!all.length) return "*(No concepts registered.)*";
  const defined = new Map(all.map(c => [c.name.toLowerCase(), c]));
  const lines = ["```mermaid", "graph LR"];
  for (const c of all) lines.push(`  ${conceptId(c.name)}["${escapeMermaid(c.name)}"]`);
  for (const c of all) {
    for (const p of c.parents) lines.push(`  ${conceptId(p)} --> ${conceptId(c.name)}`);
    for (const child of c.children) lines.push(`  ${conceptId(c.name)} --> ${conceptId(child)}`);
    for (const relName of c.related) lines.push(`  ${conceptId(c.name)} -.-> ${conceptId(relName)}`);
  }
  for (const c of all) {
    const repo = ctx.repos.find(r => r.name === c.repo);
    if (!repo) continue;
    const branch = repo.branch || "main";
    lines.push(`  click ${conceptId(c.name)} "https://github.com/JeanHuguesRobert/${repo.name}/blob/${branch}/research/concepts.md#${c.slug}" "Open ${escapeMermaid(c.name)}"`);
  }
  lines.push("```");
  const orphans = all.filter(c => !c.parents.length && !c.children.length && !c.related.length);
  if (orphans.length) lines.push(`\n*Orphan concepts: ${orphans.map(c => `\`${c.name}\` (${c.repo})`).join(", ")}.*`);
  const missing = [];
  for (const c of all) {
    for (const ref of [...c.parents, ...c.children, ...c.related]) {
      if (!defined.has(ref.toLowerCase())) missing.push(ref);
    }
  }
  if (missing.length) lines.push(`\n*Referenced but undefined: ${[...new Set(missing)].map(x => `\`${x}\``).join(", ")}.*`);
  return lines.join("\n");
}

function checkConcepts(selected, allLoaded) {
  const defined = new Map();
  for (const c of allLoaded.flatMap(r => r.concepts)) {
    const key = c.name.toLowerCase();
    if (!defined.has(key)) defined.set(key, []);
    defined.get(key).push(c);
  }
  return selected.map(r => {
    const warnings = [];
    const concepts = r.concepts.map(c => {
      const cw = [];
      if (!c.type) cw.push("missing Type");
      if (!c.scope) cw.push("missing Scope");
      if (!c.status) cw.push("missing Status");
      if (!c.short_definition) cw.push("missing Short definition");
      for (const ref of [...c.parents, ...c.children, ...c.related]) {
        if (!defined.has(ref.toLowerCase())) cw.push(`undefined concept reference: ${ref}`);
      }
      const dups = defined.get(c.name.toLowerCase()) || [];
      if (dups.length > 1) cw.push(`duplicate concept name across repos: ${dups.map(x => x.repo).join(", ")}`);
      warnings.push(...cw.map(w => `${c.name}: ${w}`));
      return { name: c.name, warnings: cw, errors: [] };
    });
    return { repo: r.repo, ok: r.ok, reason: r.reason || null, concepts, warnings, errors: [] };
  });
}

function buildIndexSets(repo) {
  const full = path.join(repo.path, "research", INDEX_FILE);
  const empty = { all: new Set(), published: new Set() };
  if (!fs.existsSync(full)) return empty;
  const raw = fs.readFileSync(full, "utf8");
  const all = resolveLinksInText(repo, full, raw);
  const published = resolveLinksInText(repo, full, extractHeadingSection(raw, "Published"));
  return { all, published };
}

function resolveLinksInText(repo, fromFile, text) {
  const refs = new Set();
  for (const link of extractMarkdownLinks(text)) {
    const target = resolveLocalLink(repo, fromFile, link.url);
    if (target) refs.add(path.resolve(target));
  }
  return refs;
}

function extractMarkdownLinks(raw) {
  const text = stripFencedCode(raw);
  const links = [];
  const re = /\[[^\]]+\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g;
  let m;
  while ((m = re.exec(text))) {
    const url = decodeURIComponent(m[1]).split("#")[0];
    if (!url || /^mailto:/i.test(url)) continue;
    if (!/\.md$/i.test(url) && !/\.md\?/i.test(url) && !/\/blob\/[^/]+\/.+\.md$/i.test(url)) continue;
    links.push({ url });
  }
  return links;
}

function resolveMarkdownLink(ctx, doc, url) {
  const github = parseGithubBlob(url);
  if (github) {
    const repo = ctx.repos.find(r => r.name.toLowerCase() === github.repo.toLowerCase());
    if (!repo) return null;
    const full = path.join(repo.path, github.path);
    return fs.existsSync(full) ? { repo: repo.name, full_path: path.resolve(full) } : null;
  }
  const repo = ctx.repos.find(r => r.name === doc.repo);
  if (!repo) return null;
  const full = resolveLocalLink(repo, doc.full_path, url);
  return full ? { repo: repo.name, full_path: path.resolve(full) } : null;
}

function resolveLocalLink(repo, fromFile, url) {
  if (/^[a-z]+:/i.test(url)) return null;
  const clean = url.split("#")[0];
  if (!clean) return null;
  const full = path.resolve(path.dirname(fromFile), clean);
  if (!isInside(repo.path, full) || !fs.existsSync(full)) return null;
  return full;
}

function parseGithubBlob(url) {
  const m = String(url).match(/^https:\/\/github\.com\/([^/]+)\/([^/]+)\/blob\/([^/]+)\/(.+\.md)$/i);
  if (!m) return null;
  return { owner: m[1], repo: m[2], branch: m[3], path: m[4] };
}

function githubUrl(repo, relPath) {
  const branch = repo.branch || "main";
  return `https://github.com/JeanHuguesRobert/${repo.name}/blob/${branch}/${relPath}`;
}

function verifyGit(ctx) {
  return ctx.repos.map(repo => {
    const status = git(repo.path, ["status", "--porcelain"], { ok: true }).split(/\r?\n/).filter(line => line.trim());
    let behind = 0;
    let ahead = 0;
    const counts = git(repo.path, ["rev-list", "--left-right", "--count", "@{upstream}...HEAD"], { ok: true }).trim().split(/\s+/);
    if (counts.length === 2) {
      behind = Number(counts[0]) || 0;
      ahead = Number(counts[1]) || 0;
    }
    const ignored = repo.policy.ignore_dirty || [];
    const dirty = status.filter(line => !ignored.some(pattern => globMatch(gitStatusPath(line), pattern)));
    return { repo: repo.name, branch: repo.branch, behind, ahead, dirty_count: dirty.length, dirty };
  });
}

function gitStatusPath(line) {
  const raw = String(line).length > 3 ? String(line).slice(3).trim() : String(line).trim();
  const renamed = raw.includes(" -> ") ? raw.slice(raw.lastIndexOf(" -> ") + 4) : raw;
  return unquote(renamed).replace(/\\/g, "/");
}

function loadContext() {
  const configPath = findConfig();
  if (!configPath) throw new Error("No .cogentia.json found. Use --registry <path> or COGENTIA_REGISTRY.");
  const raw = JSON.parse(fs.readFileSync(configPath, "utf8"));
  const repos = (raw.repos || []).map(r => {
    const policy = {
      ...(DEFAULT_REPO_POLICIES[r.name] || {}),
      ...(raw.policies?.[r.name] || raw.repo_policies?.[r.name] || {}),
    };
    return {
      name: r.name,
      path: path.resolve(r.path),
      branch: r.branch || "main",
      added: r.added,
      policy: { default_scope: "all", ...policy },
    };
  });
  return { configPath, registryRoot: path.dirname(configPath), config: raw, repos };
}

function findConfig() {
  const explicit = valueFlag("--registry") || process.env.COGENTIA_REGISTRY;
  if (explicit) {
    const p = path.resolve(explicit);
    if (fs.existsSync(p) && fs.statSync(p).isDirectory()) return path.join(p, CONFIG_FILE);
    return p;
  }
  let cur = process.cwd();
  while (true) {
    const p = path.join(cur, CONFIG_FILE);
    if (fs.existsSync(p)) return p;
    const parent = path.dirname(cur);
    if (parent === cur) break;
    cur = parent;
  }
  const known = "C:\\tweesic\\JeanHuguesRobert\\.cogentia.json";
  return fs.existsSync(known) ? known : null;
}

function continuationsDir(ctx) {
  return path.join(ctx.registryRoot || path.dirname(ctx.configPath), ".cogentia", "continuations");
}

function continuationPath(ctx, id) {
  if (!/^ctn_[a-f0-9]{8,}$/i.test(id)) throw new Error(`Invalid continuation id: ${id}`);
  return path.join(continuationsDir(ctx), `${id}.json`);
}

function continuationId() {
  return `ctn_${randomBytes(4).toString("hex")}`;
}

function loadContinuations(ctx) {
  const dir = continuationsDir(ctx);
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(file => /^ctn_[a-f0-9]+\.json$/i.test(file))
    .map(file => normalizeContinuation(readJson(path.join(dir, file))))
    .filter(Boolean);
}

function loadContinuation(ctx, id) {
  const full = continuationPath(ctx, id);
  if (!fs.existsSync(full)) throw new Error(`Continuation not found: ${id}`);
  return normalizeContinuation(readJson(full));
}

function saveContinuation(ctx, continuation) {
  ensureDir(continuationsDir(ctx));
  fs.writeFileSync(continuationPath(ctx, continuation.id), `${JSON.stringify(continuation, null, 2)}\n`, "utf8");
}

function emitContinuation(ctx, request) {
  const dedupeKey = request.dedupe_key || "";
  if (dedupeKey) {
    const existing = loadContinuations(ctx).find(c => c.status === "active" && c.dedupe_key === dedupeKey);
    if (existing) return { ok: true, created: false, path: continuationPath(ctx, existing.id), continuation: existing };
  }
  const now = new Date().toISOString();
  const id = continuationId();
  const continuation = {
    type: "continuation",
    protocol: CONTINUATION_PROTOCOL,
    id,
    continuation_id: id,
    status: "active",
    kind: request.kind || "judgment",
    title: request.title || request.kind || "External judgment required",
    question: request.question,
    priority: Number(request.priority || 0) || 0,
    dedupe_key: dedupeKey,
    subject: request.subject || {},
    context: request.context || {},
    expected_response: request.expected_response || {
      format: "json",
      required: ["decision", "reason"],
    },
    requester: {
      command: process.argv.join(" "),
      cwd: process.cwd(),
      registry: ctx.configPath,
    },
    created_at: now,
    updated_at: now,
    resolution: null,
    history: [{ at: now, event: "emitted" }],
    resume: {
      command: `node scripts/cogentia.js continuation resolve ${id} <result.json>`,
    },
  };
  saveContinuation(ctx, continuation);
  return { ok: true, created: true, path: continuationPath(ctx, continuation.id), continuation };
}

function normalizeContinuation(c) {
  if (!c || typeof c !== "object") return c;
  const contextKind = typeof c.context?.kind === "string" ? c.context.kind : "";
  const task = typeof c.task === "string" ? c.task : "";
  const title = c.title || (task ? task.slice(0, 96) : contextKind || c.kind || "Continuation");
  const createdAt = c.created_at || c.createdAt || "";
  return {
    ...c,
    continuation_id: c.continuation_id || c.id,
    kind: c.kind || contextKind || "judgment",
    title,
    question: c.question || task || title,
    priority: Number(c.priority || 0) || 0,
    dedupe_key: c.dedupe_key || "",
    subject: c.subject || legacySubject(c),
    created_at: createdAt,
    updated_at: c.updated_at || c.updatedAt || createdAt,
    history: Array.isArray(c.history) ? c.history : [],
  };
}

function legacySubject(c) {
  if (c.context?.repo) return { repo: c.context.repo };
  if (c.topicId) return { topic: c.topicId };
  return {};
}

function readContinuationContext() {
  const contextJson = valueFlag("--context-json");
  const contextFile = valueFlag("--context-file");
  if (contextJson) return parseJsonText(contextJson, "--context-json");
  if (contextFile) {
    const full = path.resolve(contextFile);
    const raw = fs.readFileSync(full, "utf8");
    if (/\.json$/i.test(full)) return parseJsonText(raw, contextFile);
    return { file: full, text: raw };
  }
  return {};
}

function readContinuationPayload() {
  const payloadFlag = valueFlag("--payload");
  const candidate = payloadFlag || (argv[0] && fs.existsSync(path.resolve(argv[0])) ? argv.shift() : "");
  if (!candidate) return {};
  return parseJsonText(fs.readFileSync(path.resolve(candidate), "utf8"), candidate);
}

function readJson(full) {
  return parseJsonText(fs.readFileSync(full, "utf8"), full);
}

function parseJsonText(raw, label) {
  try {
    return JSON.parse(raw);
  } catch (e) {
    throw new Error(`Cannot parse JSON from ${label}: ${e.message}`);
  }
}

function listMarkdown(root) {
  const out = [];
  walk(root, out);
  return out;
}

function walk(dir, out) {
  if (!fs.existsSync(dir)) return;
  const base = path.basename(dir);
  if (BUILTIN_SKIP_DIRS.has(base)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (entry.isFile() && /\.md$/i.test(entry.name)) out.push(full);
  }
}

function loadIgnore(repoPath) {
  const patterns = [
    ...[...BUILTIN_IGNORED_BASENAMES],
  ];
  const full = path.join(repoPath, ".cogentiaignore");
  if (fs.existsSync(full)) {
    for (const line of fs.readFileSync(full, "utf8").split(/\r?\n/)) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith("#")) patterns.push(trimmed);
    }
  }
  return patterns;
}

function matchesIgnore(relPath, patterns) {
  const clean = relPath.replace(/\\/g, "/");
  const base = path.basename(clean);
  return patterns.some(pattern => {
    if (BUILTIN_IGNORED_BASENAMES.has(pattern)) return base.toLowerCase() === pattern.toLowerCase();
    return globMatch(clean, pattern) || globMatch(base, pattern);
  });
}

function globMatch(value, pattern) {
  const cleanValue = String(value).replace(/\\/g, "/");
  const p = String(pattern).replace(/\\/g, "/");
  if (p.endsWith("/**")) {
    const prefix = p.slice(0, -3);
    if (cleanValue === prefix || cleanValue.startsWith(`${prefix}/`)) return true;
  }
  let source = "";
  for (let i = 0; i < p.length; i++) {
    if (p[i] === "*" && p[i + 1] === "*") {
      source += ".*";
      i++;
    } else if (p[i] === "*") {
      source += "[^/]*";
    } else {
      source += escapeRegExp(p[i]);
    }
  }
  const re = new RegExp(`^${source}$`, "i");
  return re.test(cleanValue);
}

function parseFrontmatter(raw) {
  if (!raw.startsWith("---")) return { data: {}, body: raw };
  const end = raw.indexOf("\n---", 3);
  if (end < 0) return { data: {}, body: raw };
  const yaml = raw.slice(3, end).trim();
  const data = {};
  for (const line of yaml.split(/\r?\n/)) {
    const m = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!m) continue;
    data[m[1]] = unquote(m[2].trim());
  }
  return { data, body: raw.slice(end + 4) };
}

function extractTitle(raw, full, fm) {
  if (fm.title) return String(fm.title);
  const m = raw.match(/^#\s+(.+)$/m);
  if (m) return m[1].trim();
  return path.basename(full, ".md").replace(/[-_]+/g, " ");
}

function buildGitDateIndex(repo) {
  const raw = git(repo.path, ["log", "--date=short", "--format=@@@%cs%x09%s", "--name-only", "--", "*.md"], { ok: true });
  const index = new Map();
  let commit = null;
  for (const line of raw.split(/\r?\n/)) {
    if (!line.trim()) continue;
    if (line.startsWith("@@@")) {
      const [date, ...rest] = line.slice(3).split("\t");
      commit = { date, subject: rest.join("\t") };
      continue;
    }
    if (!commit || !/\.md$/i.test(line)) continue;
    const relPath = line.replace(/\\/g, "/");
    if (!index.has(relPath)) index.set(relPath, { latest: null, significant: null, first: null });
    const item = index.get(relPath);
    if (!item.latest) item.latest = commit;
    if (!item.significant && !MAINTENANCE_RE.test(commit.subject)) item.significant = commit;
    item.first = commit;
  }
  return index;
}

function gitDates(gitIndex, relPath) {
  const item = gitIndex.get(relPath.replace(/\\/g, "/"));
  const latest = item?.latest || null;
  const significant = item?.significant || latest;
  const first = item?.first || latest;
  return {
    created: { date: first?.date || "", source: first ? "git:first-commit" : "unknown" },
    updated: { date: significant?.date || "", source: significant ? "git:last-non-bulk" : "unknown", subject: significant?.subject || "" },
  };
}

function filterDocuments(docs, filter) {
  let list = docs;
  if (filter.repo !== "all") list = list.filter(d => d.repo === filter.repo);
  if (!filter.includeIgnored) list = list.filter(d => !d.index.ignored);
  if (filter.role && filter.role !== "all") list = list.filter(d => d.role === filter.role);
  if (filter.notIndexed) list = list.filter(isIndexGap);
  if (filter.q) {
    const q = filter.q.toLowerCase();
    list = list.filter(d => `${d.title} ${d.rel} ${d.repo} ${d.role}`.toLowerCase().includes(q));
  }
  list = [...list].sort(compareDocs(filter.sort));
  if (filter.limit) list = list.slice(0, filter.limit);
  return list;
}

function isIndexGap(d) {
  return !d.index.ignored
    && d.role !== "alias"
    && d.role !== "index"
    && !d.index.referenced
    && d.rel !== "research/index.md";
}

function isGeneratedNavigationDoc(d) {
  return /^research\/(corpus-status|documents)\.md$/i.test(d.rel);
}

function documentJudgmentRequests(inventory, repoArg, options = {}) {
  const docs = inventory.documents
    .filter(d => !d.index.ignored)
    .filter(d => repoArg === "all" || d.repo === repoArg)
    .filter(d => !isGeneratedNavigationDoc(d))
    .sort(compareDocs("repo"));
  const requests = [];
  for (const doc of docs) {
    const reasons = [];
    if (doc.role === "unknown" || doc.role_confidence === "weak") {
      reasons.push("document role is unknown or weakly inferred");
    }
    if (doc.role === "derived") {
      reasons.push("derived document may need judgment: asymmetric derived product or symmetric sovereign source");
    }
    if (options.includeInferredSource && doc.role === "source" && doc.role_confidence === "medium" && doc.rel.startsWith("research/")) {
      const explicit = String(doc.frontmatter.document_role || doc.frontmatter.corpus_role || doc.frontmatter.role || "");
      if (!explicit) reasons.push("source role is inferred from research path, not explicit frontmatter");
    }
    if (!reasons.length) continue;
    const ref = `${doc.repo}/${doc.rel}`;
    requests.push({
      kind: "document_role_review",
      title: `Classify ${ref}`,
      question: `Decide the corpus role of ${ref}. In particular, say whether it is a sovereign source document, an asymmetric derived product, an alias/redirect, or a symmetric derived document that should temporarily count as sovereign source.`,
      priority: doc.role === "unknown" ? 2 : 1,
      dedupe_key: `document_role_review:${ref}`,
      subject: {
        repo: doc.repo,
        path: doc.rel,
        title: doc.title,
        github_url: doc.github_url,
      },
      context: {
        reasons,
        current_role: doc.role,
        role_source: doc.role_source,
        role_confidence: doc.role_confidence,
        frontmatter: doc.frontmatter,
        size: doc.size,
        last_significant_update: doc.updated,
      },
      expected_response: {
        format: "json",
        required: ["document_role", "reason"],
        optional: ["frontmatter_patch", "index_action", "redirect_to"],
      },
    });
  }
  return requests;
}

function docsFilter(repoArg) {
  return {
    repo: repoArg || "all",
    role: valueFlag("--role") || "all",
    q: valueFlag("--q") || "",
    notIndexed: hasFlag("--not-indexed"),
    includeIgnored: hasFlag("--include-ignored"),
    sort: valueFlag("--sort") || "updated",
    limit: Number(valueFlag("--limit") || 0) || null,
  };
}

function docSummary(inventory) {
  const docs = inventory.documents.filter(d => !d.index.ignored);
  const byRepo = groupBy(docs, d => d.repo);
  return {
    ok: true,
    total: docs.length,
    roles: countBy(docs, d => d.role),
    repos: [...byRepo.entries()].map(([repo, list]) => ({
      repo,
      documents: list.length,
      source: list.filter(d => d.role === "source").length,
      derived: list.filter(d => d.role === "derived").length,
      operational: list.filter(d => d.role === "operational").length,
      gaps: list.filter(isIndexGap).length,
    })),
    coupling: inventory.coupling,
  };
}

function sanitizeDoc(d) {
  const repo = d.repo;
  const branch = d.branch || "main";
  const github = d.github_url || `https://github.com/JeanHuguesRobert/${repo}/blob/${branch}/${d.rel}`;
  return {
    repo: d.repo,
    path: d.rel,
    title: d.title,
    role: d.role,
    role_source: d.role_source,
    role_confidence: d.role_confidence,
    size: d.size,
    created: d.created,
    last_significant_update: d.updated,
    links: d.links,
    index: d.index,
    full_path: d.full_path,
    github_url: github,
  };
}

function resolveDocRef(inventory, ref) {
  const clean = ref.replace(/\\/g, "/");
  const repoPrefix = clean.match(/^([^/]+)\/(.+\.md)$/i);
  if (repoPrefix) return inventory.documents.find(d => d.repo === repoPrefix[1] && d.rel === repoPrefix[2]);
  return inventory.documents.find(d => d.rel === clean || d.full_path.replace(/\\/g, "/") === clean);
}

function summarizeCoupling(edges) {
  const map = new Map();
  for (const edge of edges) {
    if (edge.from_repo === edge.to_repo) continue;
    const key = `${edge.from_repo}\t${edge.to_repo}`;
    map.set(key, (map.get(key) || 0) + 1);
  }
  return {
    repo_edges: [...map.entries()].map(([key, weight]) => {
      const [from, to] = key.split("\t");
      return { from, to, weight };
    }).sort((a, b) => b.weight - a.weight || a.from.localeCompare(b.from)),
  };
}

function summarizePlan(changes, inventory) {
  const activeDocs = inventory.documents.filter(d => !d.index.ignored);
  return {
    changes: changes.length,
    by_type: countBy(changes, c => c.type),
    by_repo: countBy(changes, c => c.repo),
    documents: activeDocs.length,
    gaps: activeDocs.filter(isIndexGap).length,
  };
}

function repoSelected(repo, options) {
  if (!options.scope || options.scope === "configured" || options.scope === "all" || options.scope === "research") return true;
  const m = options.scope.match(/^repo:(.+)$/);
  return m ? repo.name === m[1] : true;
}

function pathAllowedByScope(repo, relPath, options) {
  const scope = options.scope || "configured";
  if (scope === "all") return true;
  if (scope === "research") return relPath.startsWith("research/");
  if (scope.startsWith("repo:")) return true;
  const policyScope = repo.policy.default_scope || "all";
  if (policyScope === "research") return relPath.startsWith("research/");
  return true;
}

function stripChangeBody(change) {
  const { before, after, ...rest } = change;
  return rest;
}

function replaceSection(content, name, body) {
  const begin = `<!-- BEGIN_AUTO: ${name} -->`;
  const end = `<!-- END_AUTO: ${name} -->`;
  if (!content.includes(begin) || !content.includes(end)) return content;
  const re = new RegExp(`${escapeRegExp(begin)}[\\s\\S]*?${escapeRegExp(end)}`, "m");
  return content.replace(re, `${begin}\n${body.trim()}\n${end}`);
}

function stripAutoSections(raw) {
  return String(raw).replace(/<!--\s*BEGIN_AUTO:[\s\S]*?<!--\s*END_AUTO:[\s\S]*?-->/g, "");
}

function extractHeadingSection(raw, title) {
  const re = new RegExp(`^##\\s+${escapeRegExp(title)}\\s*$`, "mi");
  const m = re.exec(raw);
  if (!m) return "";
  const start = m.index + m[0].length;
  const rest = raw.slice(start);
  const next = rest.search(/^##\s+/m);
  return (next >= 0 ? rest.slice(0, next) : rest).trim();
}

function field(body, name) {
  const lines = String(body).split(/\r?\n/);
  const re = new RegExp(`^\\s*\\*\\*${escapeRegExp(name)}:\\*\\*\\s*(.*)$`, "i");
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(re);
    if (!m) continue;
    const inline = m[1].trim();
    if (inline) return cleanField(inline);
    const collected = [];
    for (let j = i + 1; j < lines.length; j++) {
      const line = lines[j];
      const trimmed = line.trim();
      if (/^\*\*[^*]+:\*\*/.test(trimmed) || /^#{1,6}\s+/.test(trimmed) || /^<!--\s*(BEGIN|END)_AUTO:/.test(trimmed) || /^---+$/.test(trimmed)) break;
      if (/^\s*-\s+/.test(line)) break;
      if (!trimmed) {
        if (collected.length) break;
        continue;
      }
      collected.push(trimmed);
    }
    return cleanField(collected.join(" "));
  }
  return "";
}

function listAfter(body, name) {
  const re = new RegExp(`\\*\\*${escapeRegExp(name)}:\\*\\*\\s*\\n([\\s\\S]*?)(?=\\n\\*\\*|\\n##|$)`, "i");
  const m = body.match(re);
  if (!m) return [];
  return m[1].split(/\r?\n/)
    .map(line => line.replace(/^\s*-\s*/, "").trim())
    .map(cleanConceptRef)
    .filter(isUsefulListValue);
}

function snippet(lines, index) {
  return lines
    .slice(Math.max(0, index - 1), Math.min(lines.length, index + 2))
    .map(line => line.trim())
    .filter(Boolean)
    .join(" / ")
    .slice(0, 500);
}

function cleanConceptRef(s) {
  return s
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/^\[([^\]]+)\]\([^)]+\).*$/, "$1")
    .replace(/`/g, "")
    .trim();
}

function cleanField(s) {
  return String(s).replace(/\s+$/g, "").trim();
}

function isUsefulListValue(s) {
  if (!s) return false;
  if (/^[-\u2014]+$/.test(s)) return false;
  if (/^#{1,6}\s+/.test(s)) return false;
  if (/^These documents link to this file/i.test(s)) return false;
  return true;
}

function stripFencedCode(raw) {
  return raw.replace(/```[\s\S]*?```/g, "");
}

function git(cwd, args, options = {}) {
  try {
    return execFileSync("git", args, { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  } catch (e) {
    if (options.ok) return "";
    throw e;
  }
}

function output(json, text) {
  if (JSON_MODE) console.log(JSON.stringify(json, null, 2));
  else console.log(text);
}

function stripContinuationBody(c) {
  return {
    id: c.id,
    status: c.status,
    kind: c.kind,
    title: c.title,
    question: c.question,
    priority: c.priority || 0,
    dedupe_key: c.dedupe_key || "",
    subject: c.subject || {},
    created_at: c.created_at,
    updated_at: c.updated_at,
    resume: c.resume,
  };
}

function formatState(repos) {
  const lines = ["\nCogentia state\n", `${pad("Repository", 18)} ${pad("Branch", 8)} Index Concepts Policy`];
  lines.push("-".repeat(70));
  for (const r of repos) lines.push(`${pad(r.name, 18)} ${pad(r.branch, 8)} ${r.index ? "yes" : "no "}   ${r.concepts ? "yes" : "no "}      ${r.policy.default_scope || "all"}`);
  return lines.join("\n");
}

function formatPlan(plan) {
  const lines = ["\nCorpus plan\n"];
  if (!plan.changes.length) {
    lines.push("No generated changes.");
    return lines.join("\n");
  }
  lines.push(`${pad("Repo", 18)} ${pad("Type", 14)} ${pad("Action", 8)} Path`);
  lines.push("-".repeat(90));
  for (const c of plan.changes) lines.push(`${pad(c.repo, 18)} ${pad(c.type, 14)} ${pad(c.action, 8)} ${c.path}`);
  lines.push("");
  lines.push(`Changes: ${plan.summary.changes}`);
  return lines.join("\n");
}

function formatApply(result) {
  const lines = ["\nCorpus apply\n", `Applied: ${result.applied.length}`];
  for (const c of result.applied) lines.push(`- ${c.repo}: ${c.path} (${c.type})`);
  if (result.skipped.length) {
    lines.push(`Skipped: ${result.skipped.length}`);
    for (const c of result.skipped) lines.push(`- ${c.repo}: ${c.path} (${c.reason})`);
  }
  return lines.join("\n");
}

function formatDocs(docs) {
  if (!docs.length) return "No documents.";
  const lines = [`\nDocuments (${docs.length})\n`];
  for (const d of docs) lines.push(`- ${d.repo}/${d.path} - ${d.title} [${d.role}]`);
  return lines.join("\n");
}

function formatSearch(matches, q) {
  if (!matches.length) return `No matches for "${q}".`;
  const lines = [`\nSearch results for "${q}" (${matches.length})\n`];
  for (const m of matches) lines.push(`- ${m.repo}/${m.path}:${m.line} - ${m.snippet}`);
  return lines.join("\n");
}

function formatDoc(d) {
  return `\n${d.repo}/${d.rel}\n${d.title}\nrole: ${d.role}\nupdated: ${d.updated.date || "-"}\nindexed: ${d.index.referenced}\n`;
}

function formatDocSummary(summary) {
  const lines = ["\nDocument summary\n", `Total: ${summary.total}`, ""];
  for (const r of summary.repos) lines.push(`${pad(r.repo, 18)} docs=${r.documents} source=${r.source} derived=${r.derived} operational=${r.operational} gaps=${r.gaps}`);
  return lines.join("\n");
}

function formatJudgments(result) {
  const lines = ["\nDocument judgments\n"];
  if (!result.needs_judgment.length) {
    lines.push("No document-role judgment candidates.");
    return lines.join("\n");
  }
  lines.push(`${pad("Repo", 18)} ${pad("Path", 46)} Reason`);
  lines.push("-".repeat(95));
  for (const req of result.needs_judgment) {
    lines.push(`${pad(req.subject.repo, 18)} ${pad(req.subject.path, 46)} ${req.context.reasons.join("; ")}`);
  }
  if (result.continuations.length) {
    lines.push("");
    lines.push(`Continuations: ${result.emitted} emitted, ${result.existing} already active.`);
  } else {
    lines.push("");
    lines.push("Run again with --emit-continuations to create active judgment requests.");
  }
  return lines.join("\n");
}

function formatConceptList(results) {
  const lines = ["\nConcepts\n"];
  for (const r of results) {
    lines.push(`${r.repo}: ${r.concepts.length}`);
    for (const c of r.concepts) lines.push(`- ${c.name} (${c.scope || "-"} / ${c.status || "-"})`);
  }
  return lines.join("\n");
}

function formatConceptCheck(results) {
  const lines = ["\nConcept check\n"];
  for (const r of results) lines.push(`${pad(r.repo, 18)} concepts=${r.concepts.length} warnings=${r.warnings.length} errors=${r.errors.length}`);
  return lines.join("\n");
}

function formatGit(results) {
  const lines = ["\nGit verify\n", `${pad("Repository", 18)} ${pad("Behind", 8, true)} ${pad("Ahead", 8, true)} ${pad("Dirty", 8, true)}`];
  lines.push("-".repeat(55));
  for (const r of results) lines.push(`${pad(r.repo, 18)} ${pad(r.behind, 8, true)} ${pad(r.ahead, 8, true)} ${pad(r.dirty_count, 8, true)}`);
  return lines.join("\n");
}

function formatContinuationEmit(result) {
  const c = result.continuation;
  const verb = result.created ? "Emitted" : "Already active";
  return `\n${verb} continuation ${c.id}\nkind: ${c.kind}\ntitle: ${c.title}\nfile: ${result.path}\n`;
}

function formatContinuationList(continuations, status) {
  const lines = [`\nContinuations (${status})\n`];
  if (!continuations.length) {
    lines.push("No continuations match.");
    return lines.join("\n");
  }
  lines.push(`${pad("ID", 14)} ${pad("Status", 10)} ${pad("Kind", 24)} ${pad("Pri", 4, true)} Title`);
  lines.push("-".repeat(90));
  for (const c of continuations) {
    lines.push(`${pad(c.id, 14)} ${pad(c.status, 10)} ${pad(c.kind, 24)} ${pad(c.priority || 0, 4, true)} ${c.title}`);
  }
  return lines.join("\n");
}

function formatContinuationInspect(c) {
  const subject = c.subject?.repo || c.subject?.path ? `${c.subject.repo || "-"} ${c.subject.path || ""}`.trim() : "-";
  return `\n${c.id}\nstatus: ${c.status}\nkind: ${c.kind}\ntitle: ${c.title}\nsubject: ${subject}\nquestion: ${c.question}\ncreated: ${c.created_at}\nupdated: ${c.updated_at}\n`;
}

function formatContinuationResolved(c) {
  return `\nContinuation ${c.id}: ${c.status}\nupdated: ${c.updated_at}\n`;
}

function formatContinuationSchema() {
  return `\n${CONTINUATION_PROTOCOL}\n\nRequired fields: id, status, kind, title, question, subject, context, expected_response.\nResolution is written by continuation resolve/cancel.\n`;
}

function continuationSchema() {
  return {
    protocol: CONTINUATION_PROTOCOL,
    storage: "<registry-root>/.cogentia/continuations/<ctn_id>.json",
    statuses: ["active", "resolved", "cancelled"],
    required: ["id", "status", "kind", "title", "question", "subject", "context", "expected_response"],
    commands: [
      "continuation emit --question <text>",
      "continuation list --status active|resolved|cancelled|all",
      "continuation inspect <id>",
      "continuation resolve <id> <result.json>",
      "continuation resume <id> <result.json>",
      "continuation cancel <id> --reason <text>",
    ],
  };
}

function compareContinuations(a, b) {
  return (b.priority || 0) - (a.priority || 0)
    || String(a.created_at || "").localeCompare(String(b.created_at || ""))
    || String(a.id).localeCompare(String(b.id));
}

function compareDocs(sort) {
  return (a, b) => {
    if (sort === "created") return (b.created.date || "").localeCompare(a.created.date || "") || a.repo.localeCompare(b.repo);
    if (sort === "size") return b.size.bytes - a.size.bytes;
    if (sort === "links") return (b.links.in_internal + b.links.in_cross_repo) - (a.links.in_internal + a.links.in_cross_repo);
    if (sort === "repo") return a.repo.localeCompare(b.repo) || a.rel.localeCompare(b.rel);
    return (b.updated.date || "").localeCompare(a.updated.date || "") || a.repo.localeCompare(b.repo);
  };
}

function countBy(list, fn) {
  const out = {};
  for (const x of list) {
    const key = fn(x);
    out[key] = (out[key] || 0) + 1;
  }
  return out;
}

function groupBy(list, fn) {
  const map = new Map();
  for (const x of list) {
    const key = fn(x);
    if (!map.has(key)) map.set(key, []);
    map.get(key).push(x);
  }
  return map;
}

function takeFlag(flag) {
  const i = argv.indexOf(flag);
  if (i < 0) return false;
  argv.splice(i, 1);
  return true;
}

function hasFlag(flag) {
  return argv.includes(flag);
}

function valueFlag(flag) {
  const i = argv.indexOf(flag);
  if (i < 0) return null;
  const value = argv[i + 1];
  argv.splice(i, 2);
  return value;
}

function optionalPositional(defaultValue = "") {
  if (!argv[0] || argv[0].startsWith("--")) return defaultValue;
  return argv.shift();
}

function fileExists(...parts) {
  return fs.existsSync(path.join(...parts));
}

function readFileIfExists(full) {
  return fs.existsSync(full) ? fs.readFileSync(full, "utf8") : "";
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function rel(root, full) {
  return path.relative(root, full).replace(/\\/g, "/");
}

function isInside(root, child) {
  const r = path.relative(path.resolve(root), path.resolve(child));
  return r === "" || (!r.startsWith("..") && !path.isAbsolute(r));
}

function sha(s) {
  return createHash("sha1").update(String(s)).digest("hex").slice(0, 12);
}

function wordCount(s) {
  return (s.match(/\b[\p{L}\p{N}'-]+\b/gu) || []).length;
}

function countHeadings(s) {
  return (s.match(/^#{1,6}\s+/gm) || []).length;
}

function unquote(s) {
  return s.replace(/^['"]|['"]$/g, "");
}

function ensureFinalNewline(s) {
  return s.endsWith("\n") ? s : `${s}\n`;
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

function pad(s, n, left = false) {
  s = String(s);
  return left ? s.padStart(n) : s.padEnd(n);
}

function slug(s) {
  return String(s).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function conceptId(s) {
  return `c_${slug(s).replace(/-/g, "_") || "concept"}`;
}

function mermaidId(s) {
  return `r_${slug(s).replace(/-/g, "_") || "repo"}`;
}

function escapeMermaid(s) {
  return String(s).replace(/"/g, "'");
}

function escapeTable(s) {
  return String(s).replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function escapeRegExp(s) {
  return String(s).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
